INSERT INTO VERSION(NUMERO)VALUES(20211);
INSERT INTO HIST_OBS_ANIMAL
SELECT 
 NULL ID,
 A.ID IDANIMAL,
 CAST(DATA_PROC AS DATE) DATA ,
 CAST(DATAREG AS TIME) HORA,
 ID_USUARIO,
 OBSERVACAO
FROM ANIMAL A
WHERE OBSERVACAO IS NOT NULL AND OBSERVACAO<>'';

INSERT INTO AUX_REBANHO(NOME,OBSERVACAO,ID_USUARIO)
VALUES('PROPRIO','ANIMAIS PROPRIO',(SELECT FIRST 1 ID FROM USERS WHERE STATUS=1));

UPDATE ANIMAL SET ID_REBANHO=1;