INSERT INTO MOVIMENTACAO_ANIMAL
 (ID_USUARIO,ID_ANIMAL,ID_PASTO_ORIGEM,ID_PASTO_DESTINO,"DATA",ID_MOTIVO,TIPO)
SELECT 
 A.ID_USUARIO,
 A.id,
 COALESCE((SELECT FIRST 1 ID_PASTO_ORIGEM FROM MOVIMENTACAO_ANIMAL
 WHERE ID_ANIMAL=A.ID),A.ID_LOCAL),
 COALESCE((SELECT FIRST 1 ID_PASTO_ORIGEM FROM MOVIMENTACAO_ANIMAL
 WHERE ID_ANIMAL=A.ID),A.ID_LOCAL),
 A.DATA_PROC,'0',
 1
FROM ANIMAL A 
WHERE A.STATUS<>-1
