unit ServiceRel;

interface

uses
  System.SysUtils, System.Classes, FireDAC.Stan.Intf, FireDAC.Stan.Option,
  FireDAC.Stan.Error, FireDAC.UI.Intf, FireDAC.Phys.Intf, FireDAC.Stan.Def,
  FireDAC.Stan.Pool, FireDAC.Stan.Async, FireDAC.Phys, FireDAC.Phys.FB,
  FireDAC.Phys.FBDef, FireDAC.FMXUI.Wait, FireDAC.Stan.Param, FireDAC.DatS,
  FireDAC.DApt.Intf, FireDAC.DApt, Data.DB, FireDAC.Comp.DataSet,
  FireDAC.Comp.Client,FMX.Dialogs,IniFiles,ppDB, ppParameter,
  ppDesignLayer, ppCtrls, ppVar, ppBands, Vcl.Imaging.pngimage, ppPrnabl,
  ppClass, ppCache, ppProd, ppReport, ppComm, ppRelatv, ppDBPipe,System.Variants,
  MidasLib,System.Math, FireDAC.Phys.IBBase, ppDBBDE;

type
  TSerRel = class(TDataModule)
    DBPRelEstoquePrev: TppDBPipeline;
    RepRelEstoquePrev: TppReport;
    dsRelEstoquePrev: TDataSource;
    RelEstoquePrev: TFDQuery;
    RelEstoquePrevMINERAL: TStringField;
    RelEstoquePrevTOTALENTRADA: TFMTBCDField;
    RelEstoquePrevTOTALSAIDA: TFMTBCDField;
    RelEstoquePrevSALDOATUAL: TFMTBCDField;
    RelEstoquePrevESTOQUEMINIMO: TFMTBCDField;
    RelEstoquePrevQTDCABATUAL: TFMTBCDField;
    RelEstoquePrevCONSUMOMEDIOCAB: TFMTBCDField;
    RelEstoquePrevCONSUMOMEDIODIA: TFMTBCDField;
    RelEstoquePrevPREVISAOEMDIAS: TFMTBCDField;
    RelEstoquePrevESTOQUEMINIMODIAS: TIntegerField;
    ppParameterList1: TppParameterList;
    ppDesignLayers1: TppDesignLayers;
    ppDesignLayer1: TppDesignLayer;
    ppHeaderBand1: TppHeaderBand;
    ppDetailBand1: TppDetailBand;
    ppFooterBand1: TppFooterBand;
    ppImage1: TppImage;
    ppImgLogoCli: TppImage;
    ppLabel1: TppLabel;
    ppDBText1: TppDBText;
    ppLabel2: TppLabel;
    ppDBText2: TppDBText;
    ppLabel3: TppLabel;
    ppDBText3: TppDBText;
    ppLabel4: TppLabel;
    ppDBText4: TppDBText;
    ppLabel5: TppLabel;
    ppDBText5: TppDBText;
    ppLabel6: TppLabel;
    ppDBText6: TppDBText;
    ppDBText7: TppDBText;
    ppDBText8: TppDBText;
    ppDBText9: TppDBText;
    ppLabel10: TppLabel;
    ppDBText10: TppDBText;
    ppLabel11: TppLabel;
    ppLabel12: TppLabel;
    ppLabel9: TppLabel;
    ppGroup1: TppGroup;
    ppGroupHeaderBand1: TppGroupHeaderBand;
    ppGroupFooterBand1: TppGroupFooterBand;
    ppShape1: TppShape;
    ppShape2: TppShape;
    ppShape3: TppShape;
    ppLabel7: TppLabel;
    ppShapeGreen: TppShape;
    RelEstoquePrevALERTA: TIntegerField;
    ppShapeYwllow: TppShape;
    ppShapeRed: TppShape;
    dsHistMov: TDataSource;
    ppReportHistMov: TppReport;
    ppHeaderBand2: TppHeaderBand;
    ppImage2: TppImage;
    ppDetailBand2: TppDetailBand;
    ppDBText11: TppDBText;
    ppDBText12: TppDBText;
    ppShape4: TppShape;
    ppFooterBand2: TppFooterBand;
    ppShape8: TppShape;
    ppLabel13: TppLabel;
    ppLabel14: TppLabel;
    ppDesignLayers2: TppDesignLayers;
    ppDesignLayer2: TppDesignLayer;
    ppParameterList2: TppParameterList;
    ppDBRelHistMov: TppDBPipeline;
    ppLine1: TppLine;
    ppLabel8: TppLabel;
    ppLabel15: TppLabel;
    ppDBText13: TppDBText;
    ppLabel16: TppLabel;
    ppDBText14: TppDBText;
    ppLine3: TppLine;
    ppLabel17: TppLabel;
    ppSystemVariable1: TppSystemVariable;
    ppSystemVariable2: TppSystemVariable;
    ppPageSummaryBand1: TppPageSummaryBand;
    ppShape5: TppShape;
    ppLabel18: TppLabel;
    ppDBCalc1: TppDBCalc;
    ppLine2: TppLine;
    ppLabel19: TppLabel;
    ppSystemVariable3: TppSystemVariable;
    ppSystemVariable4: TppSystemVariable;
    dsRelMorte: TDataSource;
    ppDBRelMorte: TppDBPipeline;
    ppReportRelMorte: TppReport;
    ppParameterList3: TppParameterList;
    ppDesignLayers3: TppDesignLayers;
    ppDesignLayer3: TppDesignLayer;
    ppHeaderBand3: TppHeaderBand;
    ppDetailBand3: TppDetailBand;
    ppFooterBand3: TppFooterBand;
    ppLine4: TppLine;
    ppLabel20: TppLabel;
    ppImage3: TppImage;
    ppImgLogoCli1: TppImage;
    ppLine5: TppLine;
    ppLabel21: TppLabel;
    ppSummaryBand1: TppSummaryBand;
    ppShape7: TppShape;
    ppLabel29: TppLabel;
    ppDBCalc2: TppDBCalc;
    ppLabel22: TppLabel;
    ppLabel23: TppLabel;
    ppLabel24: TppLabel;
    ppLabel25: TppLabel;
    ppLabel26: TppLabel;
    ppLabel27: TppLabel;
    ppLabel28: TppLabel;
    ppShape6: TppShape;
    ppDBText15: TppDBText;
    ppDBText16: TppDBText;
    ppDBText17: TppDBText;
    ppDBText18: TppDBText;
    ppDBText19: TppDBText;
    ppDBText20: TppDBText;
    ppDBText21: TppDBText;
    ppLine6: TppLine;
    qryMapaGado: TFDQuery;
    dsMapaGado: TDataSource;
    ppDBMapaGado: TppDBPipeline;
    ppReportMapaGado: TppReport;
    ppParameterList4: TppParameterList;
    ppDesignLayers4: TppDesignLayers;
    ppDesignLayer4: TppDesignLayer;
    ppHeaderBand4: TppHeaderBand;
    ppDetailBand4: TppDetailBand;
    ppFooterBand4: TppFooterBand;
    ppLabel30: TppLabel;
    ppLine7: TppLine;
    ppImage4: TppImage;
    ppImgCli: TppImage;
    ppShape9: TppShape;
    ppColumnHeaderBand1: TppColumnHeaderBand;
    ppColumnFooterBand1: TppColumnFooterBand;
    ppDBText22: TppDBText;
    ppShape10: TppShape;
    ppLabel31: TppLabel;
    ppDBText23: TppDBText;
    ppLabel32: TppLabel;
    ppDBText24: TppDBText;
    ppLabel33: TppLabel;
    ppDBText25: TppDBText;
    ppLabel34: TppLabel;
    ppDBText26: TppDBText;
    ppLabel35: TppLabel;
    ppDBText27: TppDBText;
    ppLabel36: TppLabel;
    ppLine8: TppLine;
    ppDBText28: TppDBText;
    ppLine9: TppLine;
    ppLabel37: TppLabel;
    ppSystemVariable5: TppSystemVariable;
    ppSystemVariable6: TppSystemVariable;
    ppLine10: TppLine;
    ppLabel38: TppLabel;
    ppSystemVariable7: TppSystemVariable;
    ppSystemVariable8: TppSystemVariable;
    ppLabel39: TppLabel;
    ppDBText29: TppDBText;
    ppLabel40: TppLabel;
    ppDBText30: TppDBText;
    ppSummaryBand2: TppSummaryBand;
    ppShape11: TppShape;
    ppShape12: TppShape;
    ppLabel41: TppLabel;
    ppLabel42: TppLabel;
    ppDBCalc3: TppDBCalc;
    ppLabel43: TppLabel;
    ppDBCalc4: TppDBCalc;
    ppLabel44: TppLabel;
    ppDBCalc5: TppDBCalc;
    ppLabel45: TppLabel;
    ppDBCalc6: TppDBCalc;
    ppLabel46: TppLabel;
    ppDBCalc7: TppDBCalc;
    ppLabel47: TppLabel;
    ppDBCalc8: TppDBCalc;
    ppLabel48: TppLabel;
    ppDBCalc9: TppDBCalc;
    ppLabel49: TppLabel;
    ppDBCalc10: TppDBCalc;
    ppLabel50: TppLabel;
    ppDBText31: TppDBText;
    ppLabel51: TppLabel;
    ppDBText32: TppDBText;
    ppLabel52: TppLabel;
    ppDBCalc11: TppDBCalc;
    ppLabel53: TppLabel;
    ppDBCalc12: TppDBCalc;
    ppLabel54: TppLabel;
    ppDBCalc13: TppDBCalc;
    ppLabel55: TppLabel;
    ppDBCalc14: TppDBCalc;
    dsRelForn: TDataSource;
    ppDBRelForn: TppDBPipeline;
    ppReportRelForn: TppReport;
    ppHeaderBand5: TppHeaderBand;
    ppImage5: TppImage;
    ppImage6: TppImage;
    ppLine11: TppLine;
    ppLabel56: TppLabel;
    ppDetailBand5: TppDetailBand;
    ppFooterBand5: TppFooterBand;
    ppLabel57: TppLabel;
    ppSystemVariable9: TppSystemVariable;
    ppSystemVariable10: TppSystemVariable;
    ppDesignLayers5: TppDesignLayers;
    ppDesignLayer5: TppDesignLayer;
    ppParameterList5: TppParameterList;
    ppDBText34: TppDBText;
    ppDBText35: TppDBText;
    ppDBText36: TppDBText;
    ppDBText37: TppDBText;
    ppDBText38: TppDBText;
    ppDBText39: TppDBText;
    ppDBText40: TppDBText;
    ppSummaryBand3: TppSummaryBand;
    ppShape13: TppShape;
    ppLabel66: TppLabel;
    ppDBCalc15: TppDBCalc;
    ppLabel67: TppLabel;
    ppDBCalc16: TppDBCalc;
    ppLabel68: TppLabel;
    ppDBCalc17: TppDBCalc;
    ppLabel69: TppLabel;
    ppDBCalc18: TppDBCalc;
    ppLabel70: TppLabel;
    ppDBCalc19: TppDBCalc;
    ppGroup2: TppGroup;
    ppGroupHeaderBand2: TppGroupHeaderBand;
    ppGroupFooterBand2: TppGroupFooterBand;
    ppShape17: TppShape;
    ppLabel59: TppLabel;
    ppLabel58: TppLabel;
    ppLabel60: TppLabel;
    ppLabel61: TppLabel;
    ppLabel62: TppLabel;
    ppLabel63: TppLabel;
    ppLabel64: TppLabel;
    ppLabel65: TppLabel;
    ppDBText33: TppDBText;
    ppShape14: TppShape;
    ppLabel71: TppLabel;
    ppDBText41: TppDBText;
    ppGroup3: TppGroup;
    ppGroupHeaderBand3: TppGroupHeaderBand;
    ppGroupFooterBand3: TppGroupFooterBand;
    ppShape15: TppShape;
    ppShape16: TppShape;
    ppShape18: TppShape;
    ppLabel73: TppLabel;
    ppLabel72: TppLabel;
    ppShape19: TppShape;
    ppShape20: TppShape;
    ppShape21: TppShape;
    ppShape22: TppShape;
    ppShape23: TppShape;
    ppShape24: TppShape;
    ppShape25: TppShape;
    ppShape26: TppShape;
    ppDBText42: TppDBText;
    ppShape27: TppShape;
    ppShape28: TppShape;
    ppShape29: TppShape;
    ppShape30: TppShape;
    ppShape31: TppShape;
    ppShape32: TppShape;
    ppShape33: TppShape;
    ppDBText43: TppDBText;
    ppDBText44: TppDBText;
    ppShape34: TppShape;
    ppShape35: TppShape;
    ppShape36: TppShape;
    ppShape37: TppShape;
    ppLabel74: TppLabel;
    ppDBCalc20: TppDBCalc;
    ppShape38: TppShape;
    ppDBCalc21: TppDBCalc;
    ppShape39: TppShape;
    ppDBCalc22: TppDBCalc;
    ppShape40: TppShape;
    ppDBCalc23: TppDBCalc;
    ppShape41: TppShape;
    ppDBCalc24: TppDBCalc;
    ppShape42: TppShape;
    ppDBCalc25: TppDBCalc;
    ppShape43: TppShape;
    ppDBCalc26: TppDBCalc;
    ppShape44: TppShape;
    ppDBCalc27: TppDBCalc;
    ppShape45: TppShape;
    ppLabel75: TppLabel;
    ppDBCalc28: TppDBCalc;
    ppLabel76: TppLabel;
    ppDBCalc29: TppDBCalc;
    ppLabel77: TppLabel;
    ppDBCalc30: TppDBCalc;
    ppLabel78: TppLabel;
    ppDBCalc31: TppDBCalc;
    ppFichaForneciemnto: TppReport;
    ppHeaderBand6: TppHeaderBand;
    ppImage7: TppImage;
    ppImage8: TppImage;
    ppLine12: TppLine;
    ppLabel79: TppLabel;
    ppDetailBand6: TppDetailBand;
    ppShape46: TppShape;
    ppShape47: TppShape;
    ppShape48: TppShape;
    ppShape49: TppShape;
    ppShape50: TppShape;
    ppShape51: TppShape;
    ppShape52: TppShape;
    ppShape54: TppShape;
    ppShape55: TppShape;
    ppFooterBand6: TppFooterBand;
    ppLabel80: TppLabel;
    ppSystemVariable11: TppSystemVariable;
    ppSystemVariable12: TppSystemVariable;
    ppDesignLayers6: TppDesignLayers;
    ppDesignLayer6: TppDesignLayer;
    ppParameterList6: TppParameterList;
    ppShape53: TppShape;
    ppDBFicha: TppDBPipeline;
    dsFicha: TDataSource;
    ppDBText45: TppDBText;
    ppDBText46: TppDBText;
    ppDBText48: TppDBText;
    ppDBText49: TppDBText;
    ppGroup4: TppGroup;
    ppGroupHeaderBand4: TppGroupHeaderBand;
    ppGroupFooterBand4: TppGroupFooterBand;
    ppShape65: TppShape;
    ppShape66: TppShape;
    ppShape67: TppShape;
    ppShape68: TppShape;
    ppShape69: TppShape;
    ppShape70: TppShape;
    ppShape71: TppShape;
    ppShape72: TppShape;
    ppShape73: TppShape;
    ppShape74: TppShape;
    ppShape75: TppShape;
    ppShape76: TppShape;
    ppLabel90: TppLabel;
    ppLabel91: TppLabel;
    ppLabel92: TppLabel;
    ppLabel93: TppLabel;
    ppLabel94: TppLabel;
    ppLabel95: TppLabel;
    ppLabel96: TppLabel;
    ppLabel97: TppLabel;
    ppLabel98: TppLabel;
    ppShape77: TppShape;
    ppShape78: TppShape;
    ppLabel99: TppLabel;
    ppLabel100: TppLabel;
    ppLabel101: TppLabel;
    ppDBText47: TppDBText;
    ppDBCalc32: TppDBCalc;
    ppDBCalc33: TppDBCalc;
    ppDBCalc34: TppDBCalc;
    ppShape56: TppShape;
    ppShape57: TppShape;
    ppShape58: TppShape;
    RelEntradasAnimal: TFDQuery;
    RelEntradasAnimalGTA: TStringField;
    RelEntradasAnimalPROPRIEDADEORIGEM: TStringField;
    RelEntradasAnimalPRODUTORORIGEM: TStringField;
    RelEntradasAnimalDATA_PROCESSAMENTO: TDateField;
    RelEntradasAnimalQTDE_ANIMAIS: TIntegerField;
    RelEntradasAnimalPESO_BALANCAO_ORIGEM: TFMTBCDField;
    RelEntradasAnimalPESO_BALANCAO_DESTINO: TFMTBCDField;
    RelEntradasAnimalMEDIA_IND_ENTRADA: TFMTBCDField;
    RelEntradasAnimalQUEBRA_BALANCAO: TFMTBCDField;
    ppDBRelEntradaAnimal: TppDBPipeline;
    dsEntradaAnimal: TDataSource;
    ppReportEntradaAnimal: TppReport;
    ppParameterList7: TppParameterList;
    ppDesignLayers7: TppDesignLayers;
    ppDesignLayer7: TppDesignLayer;
    ppHeaderBand7: TppHeaderBand;
    ppDetailBand7: TppDetailBand;
    ppFooterBand7: TppFooterBand;
    ppImage9: TppImage;
    ppShape59: TppShape;
    ppLabel81: TppLabel;
    ppLabel82: TppLabel;
    ppLine13: TppLine;
    ppLabel83: TppLabel;
    ppLabel84: TppLabel;
    ppLabel85: TppLabel;
    ppLabel86: TppLabel;
    ppLabel87: TppLabel;
    ppLabel88: TppLabel;
    ppLabel89: TppLabel;
    ppLabel102: TppLabel;
    ppDBText50: TppDBText;
    ppDBText51: TppDBText;
    ppDBText52: TppDBText;
    ppDBText53: TppDBText;
    ppDBText54: TppDBText;
    ppDBText55: TppDBText;
    ppDBText56: TppDBText;
    ppDBText57: TppDBText;
    ppDBText58: TppDBText;
    ppLine14: TppLine;
    ppShape60: TppShape;
    ppShape61: TppShape;
    ppShape62: TppShape;
    ppShape63: TppShape;
    ppShape64: TppShape;
    ppShape79: TppShape;
    ppShape80: TppShape;
    ppShape81: TppShape;
    ppSummaryBand4: TppSummaryBand;
    ppDBCalc35: TppDBCalc;
    ppDBCalc36: TppDBCalc;
    ppDBCalc37: TppDBCalc;
    ppDBCalc38: TppDBCalc;
    ppDBCalc39: TppDBCalc;
    ppShape82: TppShape;
    ppShape83: TppShape;
    ppShape84: TppShape;
    ppShape85: TppShape;
    ppShape86: TppShape;
    ppLine15: TppLine;
    ppLabel103: TppLabel;
    ppSystemVariable13: TppSystemVariable;
    ppSystemVariable14: TppSystemVariable;
    ppLine16: TppLine;
    dsRelSanidade: TDataSource;
    ppReportSanidadeAnalitico: TppReport;
    ppReportRelSani: TppDBPipeline;
    ppParameterList8: TppParameterList;
    ppDesignLayers8: TppDesignLayers;
    ppDesignLayer8: TppDesignLayer;
    ppHeaderBand8: TppHeaderBand;
    ppDetailBand8: TppDetailBand;
    ppFooterBand8: TppFooterBand;
    ppShape93: TppShape;
    ppShape94: TppShape;
    ppImage10: TppImage;
    ppShape95: TppShape;
    ppLabel104: TppLabel;
    ppLabel105: TppLabel;
    ppLine17: TppLine;
    ppLabel106: TppLabel;
    ppLabel107: TppLabel;
    ppDBText59: TppDBText;
    ppDBText60: TppDBText;
    ppDBText61: TppDBText;
    ppShape87: TppShape;
    ppLabel108: TppLabel;
    ppDBText62: TppDBText;
    ppDBText63: TppDBText;
    ppShape88: TppShape;
    ppLabel109: TppLabel;
    ppShape89: TppShape;
    ppLabel110: TppLabel;
    ppDBText64: TppDBText;
    ppShape90: TppShape;
    ppLabel111: TppLabel;
    ppDBText65: TppDBText;
    ppShape91: TppShape;
    ppLabel112: TppLabel;
    ppDBText66: TppDBText;
    ppSummaryBand5: TppSummaryBand;
    ppShape92: TppShape;
    ppDBCalc44: TppDBCalc;
    ppLabel113: TppLabel;
    ppLine18: TppLine;
    ppLabel114: TppLabel;
    ppSystemVariable15: TppSystemVariable;
    ppSystemVariable16: TppSystemVariable;
    ppLine19: TppLine;
    qryTmpExtratoMov: TFDQuery;
    qryTmpExtratoMovPASTOCURRAL: TStringField;
    qryTmpExtratoMovDIARIASOCUPACAO: TLargeintField;
    qryTmpExtratoMovDIAS: TIntegerField;
    qryTmpExtratoMovDIARIASMEDIAS: TLargeintField;
    dsRelDiarias: TDataSource;
    ppDBRelDiarias: TppDBPipeline;
    ppReldiarias: TppReport;
    ppHeaderBand9: TppHeaderBand;
    ppImage11: TppImage;
    ppShape96: TppShape;
    ppLabel116: TppLabel;
    ppLine20: TppLine;
    ppLabel117: TppLabel;
    ppLabel118: TppLabel;
    ppLabel119: TppLabel;
    ppDetailBand9: TppDetailBand;
    ppDBText68: TppDBText;
    ppShape97: TppShape;
    ppDBText69: TppDBText;
    ppDBText70: TppDBText;
    ppFooterBand9: TppFooterBand;
    ppLine21: TppLine;
    ppLabel121: TppLabel;
    ppSystemVariable17: TppSystemVariable;
    ppSystemVariable18: TppSystemVariable;
    ppDesignLayers9: TppDesignLayers;
    ppDesignLayer9: TppDesignLayer;
    ppParameterList9: TppParameterList;
    qryDiariasGrafico: TFDQuery;
    TGraficoConsumo: TFDQuery;
    TGraficoConsumoTabela: TFDQuery;
    TGraficoConsumoTabelaDATA_CONSUMO: TDateField;
    TGraficoConsumoTabelaPASTO: TStringField;
    TGraficoConsumoTabelaCONSUMO: TFMTBCDField;
    TGraficoConsumoTabelaQTD_ANIMAIS: TIntegerField;
    TGraficoConsumoTabelaCONSUMO_CAB: TFMTBCDField;
    qryAux: TFDQuery;
    qryTmpExtratoMovSexo: TFDQuery;
    qryTmpExtratoMovSexoPASTOCURRAL: TStringField;
    qryTmpExtratoMovSexoSEXO: TStringField;
    qryTmpExtratoMovSexoDIARIASOCUPACAO: TLargeintField;
    qryTmpExtratoMovSexoDIAS: TIntegerField;
    qryTmpExtratoMovSexoDIARIASMEDIAS: TLargeintField;
    ppDBRelDiariasSexo: TppDBPipeline;
    ppReldiariasSexo: TppReport;
    ppHeaderBand10: TppHeaderBand;
    ppImage12: TppImage;
    ppLine22: TppLine;
    ppLabel123: TppLabel;
    ppDetailBand10: TppDetailBand;
    ppShape100: TppShape;
    ppDBText71: TppDBText;
    ppDBText72: TppDBText;
    ppFooterBand10: TppFooterBand;
    ppLine23: TppLine;
    ppLabel128: TppLabel;
    ppSystemVariable19: TppSystemVariable;
    ppSystemVariable20: TppSystemVariable;
    ppDesignLayers10: TppDesignLayers;
    ppDesignLayer10: TppDesignLayer;
    ppParameterList10: TppParameterList;
    dsRelDiariasSexo: TDataSource;
    ppGroup5: TppGroup;
    ppGroupHeaderBand5: TppGroupHeaderBand;
    ppGroupFooterBand5: TppGroupFooterBand;
    ppShape102: TppShape;
    ppShape99: TppShape;
    ppLabel124: TppLabel;
    ppLabel125: TppLabel;
    ppLabel122: TppLabel;
    ppDBText67: TppDBText;
    ppLabel129: TppLabel;
    ppDBText73: TppDBText;
    ppShape103: TppShape;
    ppShape104: TppShape;
    ppDBCalc45: TppDBCalc;
    ppDBCalc46: TppDBCalc;
    ppLabel130: TppLabel;
    ppLblPeriodoSexo: TppLabel;
    ppLabel131: TppLabel;
    ppDBText74: TppDBText;
    ppSummaryBand6: TppSummaryBand;
    ppShape101: TppShape;
    ppLabel126: TppLabel;
    ppDBCalc42: TppDBCalc;
    ppLabel132: TppLabel;
    ppLabel133: TppLabel;
    ppLalblTotalMacho: TppLabel;
    ppLalblTotalFemeas: TppLabel;
    ppSummaryBand7: TppSummaryBand;
    ppShape98: TppShape;
    ppLabel120: TppLabel;
    ppDBCalc40: TppDBCalc;
    ppLabel115: TppLabel;
    ppDBCalc41: TppDBCalc;
    ppLabel127: TppLabel;
    pplblPeriodoGeral: TppLabel;
    ppLabel135: TppLabel;
    ppDBText75: TppDBText;
    ppLabel134: TppLabel;
    ppDBText76: TppDBText;
    ppLabel136: TppLabel;
    ppDBText77: TppDBText;
    qryRelEraEmbaque: TFDQuery;
    dsRelEraEmbaque: TDataSource;
    ppDBRelEraEmbaque: TppDBPipeline;
    ppRepRelEraEmbaque: TppReport;
    ppHeaderBand11: TppHeaderBand;
    ppShape112: TppShape;
    ppImage13: TppImage;
    ppShape113: TppShape;
    ppLabel137: TppLabel;
    ppLabel138: TppLabel;
    ppLine24: TppLine;
    ppLabel139: TppLabel;
    ppDetailBand11: TppDetailBand;
    ppDBText78: TppDBText;
    ppDBText81: TppDBText;
    ppLine25: TppLine;
    ppFooterBand11: TppFooterBand;
    ppLabel147: TppLabel;
    ppSystemVariable21: TppSystemVariable;
    ppSystemVariable22: TppSystemVariable;
    ppLine27: TppLine;
    ppSummaryBand8: TppSummaryBand;
    ppDesignLayers11: TppDesignLayers;
    ppDesignLayer11: TppDesignLayer;
    ppParameterList11: TppParameterList;
    ppGroup6: TppGroup;
    ppGroupHeaderBand6: TppGroupHeaderBand;
    ppGroupFooterBand6: TppGroupFooterBand;
    ppShape105: TppShape;
    ppLabel141: TppLabel;
    ppDBText82: TppDBText;
    ppLabel143: TppLabel;
    ppDBText83: TppDBText;
    ppShape106: TppShape;
    ppDBCalc43: TppDBCalc;
    ppRepRelEraEmbaqueLS: TppReport;
    ppHeaderBand12: TppHeaderBand;
    ppImage14: TppImage;
    ppLine28: TppLine;
    ppLabel140: TppLabel;
    ppDetailBand12: TppDetailBand;
    ppDBText79: TppDBText;
    ppDBText80: TppDBText;
    ppLine29: TppLine;
    ppFooterBand12: TppFooterBand;
    ppLine30: TppLine;
    ppLabel142: TppLabel;
    ppSystemVariable23: TppSystemVariable;
    ppSystemVariable24: TppSystemVariable;
    ppSummaryBand9: TppSummaryBand;
    ppDesignLayers12: TppDesignLayers;
    ppDesignLayer12: TppDesignLayer;
    ppParameterList12: TppParameterList;
    qryRelEraEmbaqueLS: TFDQuery;
    dsRelEraEmbaqueLS: TDataSource;
    ppDBRelEraEmbaquels: TppDBPipeline;
    ppShape107: TppShape;
    ppShape108: TppShape;
    ppLabel144: TppLabel;
    ppLabel145: TppLabel;
    ppShape109: TppShape;
    ppShape110: TppShape;
    ppLblLS: TppLabel;
    ppDBCalc47: TppDBCalc;
    qryRelHistObs: TFDQuery;
    dsRelHistObs: TDataSource;
    ppDBRelHistObs: TppDBPipeline;
    qryRelHistObsID: TIntegerField;
    qryRelHistObsID_LOCAL: TIntegerField;
    qryRelHistObsID_CATEGORIA: TIntegerField;
    qryRelHistObsID_RACA: TIntegerField;
    qryRelHistObsIDENTIFICACAO_1: TStringField;
    qryRelHistObsIDENTIFICACAO_2: TStringField;
    qryRelHistObsDATA_PROC: TSQLTimeStampField;
    qryRelHistObsGTA_ID: TIntegerField;
    qryRelHistObsIDADE_MESES: TIntegerField;
    qryRelHistObsPESO_ENTRADA: TFMTBCDField;
    qryRelHistObsULTIMO_PESO: TFMTBCDField;
    qryRelHistObsDATA_ULTIMO_PESO: TDateField;
    qryRelHistObsSTATUS: TIntegerField;
    qryRelHistObsDATAREG: TSQLTimeStampField;
    qryRelHistObsID_USUARIO: TIntegerField;
    qryRelHistObsDATA_SAIDA: TDateField;
    qryRelHistObsPESO_SAIDA: TFMTBCDField;
    qryRelHistObsID_PROPRIEDADE: TIntegerField;
    qryRelHistObsID_PRODUTOR: TIntegerField;
    qryRelHistObsULTIMA_ALTERACAO: TSQLTimeStampField;
    qryRelHistObsULTIMO_USUARIO: TIntegerField;
    qryRelHistObsID_LOTESAIDA: TIntegerField;
    qryRelHistObsID_VEICULO_SAIDA: TIntegerField;
    qryRelHistObsORIGEM_DADOS: TStringField;
    qryRelHistObsTIPO_SAIDA: TStringField;
    qryRelHistObsID_MOTIVO_MORTE: TIntegerField;
    qryRelHistObsID_LOTE: TIntegerField;
    qryRelHistObsVALOR_COMPRA: TFMTBCDField;
    qryRelHistObsVALOR_VENDA: TFMTBCDField;
    qryRelHistObsID_PRODUTOR_ORIGEM: TIntegerField;
    qryRelHistObsFLAG_SYNC: TIntegerField;
    qryRelHistObsDATA_SYNC: TSQLTimeStampField;
    qryRelHistObsDATA_LIBERACAO: TDateField;
    qryRelHistObsID_ULTIMO_USUARIO_ALTERACAO: TIntegerField;
    qryRelHistObsDATA_ULTIMA_ALTERACAO: TSQLTimeStampField;
    qryRelHistObsID_CONTRATO_COMPRA: TIntegerField;
    qryRelHistObsID_PRODUTOR_DESTINO_SAIDA: TIntegerField;
    qryRelHistObsIDADE_MORTE: TIntegerField;
    qryRelHistObsID_GTA_SAIDA: TIntegerField;
    qryRelHistObsOBSERVACAO: TStringField;
    qryRelHistObsTIPO_ENTRADA: TIntegerField;
    qryRelHistObsPESO_ESTIMADO: TFMTBCDField;
    qryRelHistObsDATA_PESO_ESTIMADO: TDateField;
    qryRelHistObsVALOR_CUSTO_ALIMENTAR: TFMTBCDField;
    qryRelHistObsVALOR_CUSTO_FIXO_ACU: TFMTBCDField;
    qryRelHistObsID_CATEGORIA_ATUAL: TIntegerField;
    qryRelHistObsCONSUMO_ACU: TFMTBCDField;
    qryRelHistObsID_COMUNICADO_REIDENT: TIntegerField;
    qryRelHistObsID_COMUNICADO_MORTE: TIntegerField;
    qryRelHistObsOBS_MORTE: TStringField;
    qryRelHistObsTIPO_MORTE: TIntegerField;
    qryRelHistObsDATA_REPROCESSAMENTO: TSQLTimeStampField;
    qryRelHistObsID_COM_NASCIMENTO: TIntegerField;
    qryRelHistObsIDENTIFICACAO_MAE: TStringField;
    qryRelHistObsCARIMBO_NASCIMENTO: TStringField;
    qryRelHistObsOUTRO_ERAS: TIntegerField;
    qryRelHistObsIMS_PV: TBCDField;
    qryRelHistObsFLAG_SYNC_TERCEIROS: TIntegerField;
    qryRelHistObsDATA_SYNC_TERCEIROS: TDateField;
    qryRelHistObsID_REBANHO: TIntegerField;
    qryRelHistObsRACA: TStringField;
    qryRelHistObsCATEGORIA: TStringField;
    qryRelHistObsREBANHO: TStringField;
    qryRelHistObsDATAOBS: TDateField;
    qryRelHistObsHORAOBS: TTimeField;
    qryRelHistObsUSUARIOOBS: TStringField;
    qryRelHistObsOBSHIST: TStringField;
    qryRelHistObsCURRAL: TStringField;
    ppRepHistObsManejo: TppReport;
    ppHeaderBand13: TppHeaderBand;
    ppImage15: TppImage;
    ppLine26: TppLine;
    ppLabel146: TppLabel;
    ppDetailBand13: TppDetailBand;
    ppLine31: TppLine;
    ppFooterBand13: TppFooterBand;
    ppLabel148: TppLabel;
    ppSystemVariable25: TppSystemVariable;
    ppSystemVariable26: TppSystemVariable;
    ppLine32: TppLine;
    ppSummaryBand10: TppSummaryBand;
    ppGroup7: TppGroup;
    ppGroupHeaderBand7: TppGroupHeaderBand;
    ppGroupFooterBand7: TppGroupFooterBand;
    ppDesignLayers13: TppDesignLayers;
    ppDesignLayer13: TppDesignLayer;
    ppParameterList13: TppParameterList;
    ppGroup8: TppGroup;
    ppGroupHeaderBand8: TppGroupHeaderBand;
    ppGroupFooterBand8: TppGroupFooterBand;
    ppShape115: TppShape;
    ppLabel151: TppLabel;
    ppLabel149: TppLabel;
    ppLabel150: TppLabel;
    ppLabel152: TppLabel;
    ppLabel153: TppLabel;
    ppLabel154: TppLabel;
    ppLabel155: TppLabel;
    ppDBText86: TppDBText;
    ppDBText87: TppDBText;
    ppDBText88: TppDBText;
    ppDBText89: TppDBText;
    ppDBText90: TppDBText;
    ppDBText91: TppDBText;
    ppDBText92: TppDBText;
    ppShape111: TppShape;
    ppLabel156: TppLabel;
    ppDBText93: TppDBText;
    ppShape114: TppShape;
    ppLabel157: TppLabel;
    ppDBText84: TppDBText;
    ppDBText85: TppDBText;
    ppDBText94: TppDBText;
    ppDBText95: TppDBText;
    ppLabel161: TppLabel;
    ppLabel162: TppLabel;
    ppLabel163: TppLabel;
    qryRelRebanhoAtivos: TFDQuery;
    dsRelRebanhoAtivos: TDataSource;
    ppDBPRelRebanhoAtivos: TppDBPipeline;
    ppRepRebanhoAtivo: TppReport;
    ppHeaderBand14: TppHeaderBand;
    ppImage16: TppImage;
    ppLine33: TppLine;
    ppLabel158: TppLabel;
    ppDetailBand14: TppDetailBand;
    ppLine34: TppLine;
    ppDBText97: TppDBText;
    ppFooterBand14: TppFooterBand;
    ppLabel159: TppLabel;
    ppSystemVariable27: TppSystemVariable;
    ppSystemVariable28: TppSystemVariable;
    ppLine35: TppLine;
    ppSummaryBand11: TppSummaryBand;
    ppGroup9: TppGroup;
    ppGroupHeaderBand9: TppGroupHeaderBand;
    ppShape116: TppShape;
    ppLabel160: TppLabel;
    ppDBText100: TppDBText;
    ppGroupFooterBand9: TppGroupFooterBand;
    ppGroup10: TppGroup;
    ppGroupHeaderBand10: TppGroupHeaderBand;
    ppShape117: TppShape;
    ppLabel164: TppLabel;
    ppLabel165: TppLabel;
    ppGroupFooterBand10: TppGroupFooterBand;
    ppDesignLayers14: TppDesignLayers;
    ppDesignLayer14: TppDesignLayer;
    ppParameterList14: TppParameterList;
    qryRelRebanhoAtivosREBANHO: TStringField;
    qryRelRebanhoAtivosCURRAL: TStringField;
    qryRelRebanhoAtivosSEXO: TStringField;
    qryRelRebanhoAtivosMEDIA_ULTIMA_PESAGEM: TFMTBCDField;
    qryRelRebanhoAtivosPRIMEIRA_ENTRDA: TSQLTimeStampField;
    qryRelRebanhoAtivosULTIM_ENTRDA: TSQLTimeStampField;
    ppLabel167: TppLabel;
    ppLabel168: TppLabel;
    ppLabel169: TppLabel;
    ppLabel170: TppLabel;
    ppDBText101: TppDBText;
    ppShape118: TppShape;
    ppDBText96: TppDBText;
    ppDBText98: TppDBText;
    ppDBText99: TppDBText;
    ppDBText102: TppDBText;
    ppShape119: TppShape;
    ppShape120: TppShape;
    ppDBCalc48: TppDBCalc;
    ppDBCalc49: TppDBCalc;
    qryRelRebanhoAtivosCOUNT: TIntegerField;
    ppShape121: TppShape;
    ppLabel166: TppLabel;
    ppLabel171: TppLabel;
    ppShape122: TppShape;
    ppLabel172: TppLabel;
    ppLabel173: TppLabel;
    ppDBCalc50: TppDBCalc;
    ppDBCalc51: TppDBCalc;
    ppDBCalc52: TppDBCalc;
    ppDBCalc53: TppDBCalc;
    dsLista: TDataSource;
    ppDBLista: TppDBPipeline;
    ppRepLista: TppReport;
    ppParameterList16: TppParameterList;
    ppDesignLayers16: TppDesignLayers;
    ppDesignLayer16: TppDesignLayer;
    ppHeaderBand16: TppHeaderBand;
    ppDetailBand16: TppDetailBand;
    ppFooterBand16: TppFooterBand;
    ppImgLogoCliente: TppImage;
    ppLabel184: TppLabel;
    ppLine38: TppLine;
    ppImage20: TppImage;
    ppGroup12: TppGroup;
    ppGroupHeaderBand12: TppGroupHeaderBand;
    ppGroupFooterBand12: TppGroupFooterBand;
    ppShape128: TppShape;
    ppShape129: TppShape;
    ppDBText109: TppDBText;
    ppLabel185: TppLabel;
    ppLabel186: TppLabel;
    ppLabel187: TppLabel;
    ppLabel188: TppLabel;
    ppLabel189: TppLabel;
    ppLabel190: TppLabel;
    ppShape130: TppShape;
    ppDBText110: TppDBText;
    ppDBText111: TppDBText;
    ppDBText112: TppDBText;
    ppDBText113: TppDBText;
    ppDBText114: TppDBText;
    ppShape131: TppShape;
    ppLabel191: TppLabel;
    ppDBCalc54: TppDBCalc;
    ppLine39: TppLine;
    ppLabel192: TppLabel;
    ppSystemVariable31: TppSystemVariable;
    ppSystemVariable32: TppSystemVariable;
    ppSummaryBand13: TppSummaryBand;
    ppShape132: TppShape;
    ppLabel193: TppLabel;
    ppDBCalc55: TppDBCalc;
    ppLabel174: TppLabel;
    ppDBText103: TppDBText;
    ppShape123: TppShape;
    ppLabel175: TppLabel;
    ppShape124: TppShape;
    ppLblPropriedade: TppLabel;
    ppLabel176: TppLabel;
    ppDBText104: TppDBText;
    ppLabel177: TppLabel;
    ppDBText105: TppDBText;
    ppLabel178: TppLabel;
    ppDBCalc56: TppDBCalc;
    ppLabel179: TppLabel;
    ppDBCalc57: TppDBCalc;
    qryRelHistObsPESO_ENTRADA_CONF: TFMTBCDField;
    qryRelHistObsDATA_ENTRADA_CONF: TDateField;
    qryRelHistObsID_CONTRATO: TIntegerField;
    qryRelHistObsID_BASE_CAMPO: TIntegerField;
    qryRelHistObsBASE_CAMPO_SYNC: TIntegerField;
    qryRelHistObsBASE_CAMPO_DT_SYNC: TDateField;
    qryRelHistObsBLOQUEIO: TIntegerField;
    qryRelHistObsDATA_NASCIMENTO: TDateField;
    qryRelHistMovRebanho: TFDQuery;
    qryRelHistMovRebanhoDATA: TDateField;
    qryRelHistMovRebanhoIDENTIFICACAO_1: TStringField;
    qryRelHistMovRebanhoIDENTIFICACAO_2: TStringField;
    qryRelHistMovRebanhoREBANHOORIGEM: TStringField;
    qryRelHistMovRebanhoREBANHODESTINO: TStringField;
    dsRelHistMovRebanho: TDataSource;
    ppRepHistMovRebanho: TppReport;
    ppHeaderBand15: TppHeaderBand;
    ppImage17: TppImage;
    ppShape125: TppShape;
    ppLabel180: TppLabel;
    ppLabel181: TppLabel;
    ppLine36: TppLine;
    ppLabel182: TppLabel;
    ppLabel183: TppLabel;
    ppLabel194: TppLabel;
    ppDetailBand15: TppDetailBand;
    ppDBText106: TppDBText;
    ppDBText107: TppDBText;
    ppShape126: TppShape;
    ppDBText108: TppDBText;
    ppDBText115: TppDBText;
    ppPageSummaryBand2: TppPageSummaryBand;
    ppShape127: TppShape;
    ppLabel195: TppLabel;
    ppDBCalc58: TppDBCalc;
    ppFooterBand15: TppFooterBand;
    ppLine37: TppLine;
    ppLabel196: TppLabel;
    ppSystemVariable29: TppSystemVariable;
    ppSystemVariable30: TppSystemVariable;
    ppDesignLayers15: TppDesignLayers;
    ppDesignLayer15: TppDesignLayer;
    ppParameterList15: TppParameterList;
    ppDBRelHistMovRebanho: TppDBPipeline;
    ppLabel197: TppLabel;
    ppDBText116: TppDBText;
    qryMapaGadoPASTO: TStringField;
    qryMapaGadoQTDCAB: TIntegerField;
    qryMapaGadoPESO_ESTIMADO: TFMTBCDField;
    qryMapaGadoUA: TFMTBCDField;
    qryMapaGadoPESO_ENTRADA: TFMTBCDField;
    qryMapaGadoULTIMO_PESO: TFMTBCDField;
    qryMapaGadoAREA_HECTARES: TFMTBCDField;
    qryMapaGadoUAH: TFMTBCDField;
    qryMapaGadoGMD: TFloatField;
    qryMapaGadoTOTALARROBA: TFMTBCDField;
    qryMapaGadoMACHOS: TIntegerField;
    qryMapaGadoFEMEAS: TIntegerField;
    qryMapaGadoDIAS: TFloatField;
    ppDBRelEra: TppDBPipeline;
    ppRepRelEra: TppReport;
    ppHeaderBand17: TppHeaderBand;
    ppImage18: TppImage;
    ppShape133: TppShape;
    ppLabel198: TppLabel;
    ppLine40: TppLine;
    ppLabel200: TppLabel;
    ppLabel202: TppLabel;
    ppLabel203: TppLabel;
    ppDetailBand17: TppDetailBand;
    ppShape134: TppShape;
    ppDBText117: TppDBText;
    ppDBText120: TppDBText;
    ppDBText121: TppDBText;
    ppPageSummaryBand3: TppPageSummaryBand;
    ppShape135: TppShape;
    ppLabel204: TppLabel;
    ppDBCalc59: TppDBCalc;
    ppFooterBand17: TppFooterBand;
    ppLine41: TppLine;
    ppLabel205: TppLabel;
    ppSystemVariable33: TppSystemVariable;
    ppSystemVariable34: TppSystemVariable;
    ppDesignLayers17: TppDesignLayers;
    ppDesignLayer17: TppDesignLayer;
    ppParameterList17: TppParameterList;
    qryRelEra: TFDQuery;
    dsRelEra: TDataSource;
    qryRelEraSEXO: TStringField;
    qryRelEraFAIXA: TStringField;
    qryRelEraQTDE: TIntegerField;
    TRelSaida: TFDQuery;
    dsRelSaida: TDataSource;
    ppRepRelSaida: TppReport;
    ppHeaderBand18: TppHeaderBand;
    ppImage19: TppImage;
    ppLabel199: TppLabel;
    ppDetailBand18: TppDetailBand;
    ppFooterBand18: TppFooterBand;
    ppLine44: TppLine;
    ppLabel208: TppLabel;
    ppSystemVariable35: TppSystemVariable;
    ppSystemVariable36: TppSystemVariable;
    ppSummaryBand12: TppSummaryBand;
    ppDesignLayers18: TppDesignLayers;
    ppDesignLayer18: TppDesignLayer;
    ppParameterList18: TppParameterList;
    DBRelSaida: TppDBPipeline;
    TRelSaidaID_ANIMAL: TIntegerField;
    TRelSaidaDATA_ENTRADA: TDateField;
    TRelSaidaDATA_ENT_CONF: TDateField;
    TRelSaidaDATA_SAIDA: TDateField;
    TRelSaidaPESO_PROJ: TFloatField;
    TRelSaidaGTP_PROJ: TFloatField;
    TRelSaidaGMD_PROJ: TFloatField;
    TRelSaidaPESO_CARCACA_PROJ: TFloatField;
    TRelSaidaPESO_ENTRADA: TFloatField;
    TRelSaidaPESO_ENT_CONF: TFloatField;
    TRelSaidaPESO_SAIDA: TFloatField;
    TRelSaidaDIAS_CONF: TIntegerField;
    TRelSaidaDIAS_TOTAL: TIntegerField;
    TRelSaidaDIAS_ALIMENTAR: TIntegerField;
    TRelSaidaGTP_REAL: TFloatField;
    TRelSaidaGMD_DIAS_TOTAL: TFloatField;
    TRelSaidaGMD_DIAS_CONF: TFloatField;
    TRelSaidaGMD_DIAS_ALIMENTAR: TFloatField;
    TRelSaidaPESO_CARCACA_REAL: TFloatField;
    TRelSaidaRC: TFloatField;
    TRelSaidaPESO_SAIDA_ARROB: TFloatField;
    TRelSaidaPESO_ENTRADA_ARROB: TFloatField;
    TRelSaidaPESO_ENT_CONF_ARROB: TFloatField;
    TRelSaidaGTP_ARROB_P_CONF: TFloatField;
    TRelSaidaGTP_ARROB_P_ENT: TFloatField;
    TRelSaidaGMD_RC: TFloatField;
    TRelSaidaPESO_CARCACA_ARROB: TFloatField;
    TRelSaidaCONSUMO_MN_KG_CAB_TOTAL: TFloatField;
    TRelSaidaCONSUMO_MS_KG_CAB_TOTAL: TFloatField;
    TRelSaidaCONSUMO_MN_KG_CAB_DIA: TFloatField;
    TRelSaidaCONSUMO_MS_KG_CAB_DIA: TFloatField;
    TRelSaidaCUSTO_COMPRA: TFloatField;
    TRelSaidaVALOR_VENDA: TFloatField;
    TRelSaidaCUSTO_ALIMENTAR: TFloatField;
    TRelSaidaCUSTO_FIXO: TFloatField;
    TRelSaidaCUSTO_SANIDADE: TFloatField;
    TRelSaidaCUSTO_TOTAL: TFloatField;
    TRelSaidaCUSTO_DIARIO_D_TOTAL: TFloatField;
    TRelSaidaCUSTO_DIARIO_D_CONF: TFloatField;
    TRelSaidaCUSTO_DIARIO_D_ALIMENTAR: TFloatField;
    TRelSaidaCUSTO_PRODUCAO: TFloatField;
    TRelSaidaVALOR_ARROB_COMPRA: TFloatField;
    TRelSaidaVALOR_ARROB_VENDA: TFloatField;
    TRelSaidaLUCRO_LIQUI: TFloatField;
    TRelSaidaCUSTO_ARROB_PROJ: TFloatField;
    TRelSaidaCUSTO_ARROB_REAL: TFloatField;
    TRelSaidaLOTE_SAIDA: TIntegerField;
    TRelSaidaULTIMO_CURRAL: TStringField;
    TRelSaidaCURRAL: TStringField;
    TRelSaidaCHIP: TStringField;
    TRelSaidaSISBOV: TStringField;
    TRelSaidaREBANHO: TStringField;
    TRelSaidaPRODUTORORIGEM: TStringField;
    TRelSaidaPROPRIEDADEORIGEM: TStringField;
    TRelSaidaPRODUTORDESTINO: TStringField;
    TRelSaidaPROPRIEDADEDESTINO: TStringField;
    ppGroup11: TppGroup;
    ppGroupHeaderBand11: TppGroupHeaderBand;
    ppGroupFooterBand11: TppGroupFooterBand;
    ppLabel207: TppLabel;
    ppLabel206: TppLabel;
    ppLabel209: TppLabel;
    ppDBText119: TppDBText;
    ppDBText122: TppDBText;
    ppLabel210: TppLabel;
    ppLabel211: TppLabel;
    TRelSaidaQTD_CAB_LOTE: TIntegerField;
    TRelSaidaTOTAL_CARCACA_LOTE: TFloatField;
    ppDBText123: TppDBText;
    ppDBText124: TppDBText;
    ppDBText125: TppDBText;
    ppLabel212: TppLabel;
    ppDBText126: TppDBText;
    TRelSaidaMEDIA_PESO_SAIDA_LOTE: TFloatField;
    ppLabel216: TppLabel;
    ppLabel217: TppLabel;
    ppLabel218: TppLabel;
    ppLabel219: TppLabel;
    ppLabel220: TppLabel;
    ppLabel221: TppLabel;
    TRelSaidaSintetico: TFDQuery;
    ppShape136: TppShape;
    TRelSaidaSinteticoLOTE_SAIDA: TIntegerField;
    TRelSaidaSinteticoDATA_SAIDA: TDateField;
    TRelSaidaSinteticoREBANHO: TStringField;
    TRelSaidaSinteticoPRODUTORDESTINO: TStringField;
    TRelSaidaSinteticoPROPRIEDADEDESTINO: TStringField;
    TRelSaidaSinteticoQTD_CAB: TIntegerField;
    TRelSaidaSinteticoPESO_ENT_CONF: TFloatField;
    TRelSaidaSinteticoPESO_ENT_CONF_ARROBA: TFloatField;
    TRelSaidaSinteticoPESO_SAIDA: TFloatField;
    TRelSaidaSinteticoPESO_SAIDA_ARROBA: TFloatField;
    TRelSaidaSinteticoPESO_PROJ: TFloatField;
    TRelSaidaSinteticoPESO_PROJ_ARROBA: TFloatField;
    TRelSaidaSinteticoPESO_MIN_SAIDA: TFloatField;
    TRelSaidaSinteticoPESO_MIN_ARROBA: TFloatField;
    TRelSaidaSinteticoPESO_MAX_SAIDA: TFloatField;
    TRelSaidaSinteticoPESO_MAX_ARROBA: TFloatField;
    TRelSaidaSinteticoGMD_TOTAL: TFloatField;
    TRelSaidaSinteticoGMD_TOTAL_ARROBA: TFloatField;
    TRelSaidaSinteticoGTP_REAL: TFloatField;
    TRelSaidaSinteticoGTP_REAL_ARROBA: TFloatField;
    TRelSaidaSinteticoGTP_TOTAL: TFloatField;
    TRelSaidaSinteticoGTP_TOTAL_ARROBA: TFloatField;
    TRelSaidaSinteticoPESO_CARCACA: TFloatField;
    TRelSaidaSinteticoTOTAL_PESO_CARCACA: TFloatField;
    TRelSaidaSinteticoARROBA_TOTAL: TFloatField;
    TRelSaidaSinteticoPESO_SAIDA_TOTAL: TFloatField;
    TRelSaidaSinteticoRC: TFloatField;
    TRelSaidaSinteticoCONSUMO_MN_KG_CAB_DIA: TFloatField;
    TRelSaidaSinteticoCONSUMO_MS_KG_CAB_DIA: TFloatField;
    TRelSaidaSinteticoCONSUMO_MN_KG_CAB_TOTAL: TFloatField;
    TRelSaidaSinteticoCONSUMO_MS_KG_CAB_TOTAL: TFloatField;
    TRelSaidaSinteticoCONVERSAO: TFloatField;
    TRelSaidaSinteticoVALOR_COMPRA: TFloatField;
    TRelSaidaSinteticoVALOR_TOTAL_COMPRA: TFloatField;
    TRelSaidaSinteticoVALOR_ALIMENTACAO: TFloatField;
    TRelSaidaSinteticoVALOR_TOTAL_ALIMENTACAO: TFloatField;
    TRelSaidaSinteticoCUSTO_FIXO: TFloatField;
    TRelSaidaSinteticoCUSTO_FIXO_TOTAL: TFloatField;
    TRelSaidaSinteticoCUSTO_SANIDADE: TFloatField;
    TRelSaidaSinteticoCUSTO_TOTAL_SANIDADE: TFloatField;
    TRelSaidaSinteticoVALOR_TOTAL_ANIMAL: TFloatField;
    TRelSaidaSinteticoVALOR_TOTAL: TFloatField;
    TRelSaidaSinteticoVALOR_ALI_CAB_DIA: TFloatField;
    TRelSaidaSinteticoVALOR_FIXO_CAB_DIA: TFloatField;
    TRelSaidaSinteticoVALOR_SANIDADE_CAB_DIA: TFloatField;
    TRelSaidaSinteticoCUSTODIARIOCABECA: TFloatField;
    ppDBText129: TppDBText;
    ppDBText130: TppDBText;
    ppDBText131: TppDBText;
    ppDBText132: TppDBText;
    ppDBText134: TppDBText;
    ppDBText118: TppDBText;
    ppLabel201: TppLabel;
    ppShape137: TppShape;
    ppLabel213: TppLabel;
    ppDBText127: TppDBText;
    ppLabel214: TppLabel;
    ppDBText128: TppDBText;
    ppLabel222: TppLabel;
    ppDBText133: TppDBText;
    ppLabel223: TppLabel;
    ppDBText135: TppDBText;
    ppLabel224: TppLabel;
    ppDBText136: TppDBText;
    ppLabel225: TppLabel;
    ppDBText137: TppDBText;
    ppLabel226: TppLabel;
    ppDBText138: TppDBText;
    ppLabel227: TppLabel;
    ppDBText139: TppDBText;
    ppLabel228: TppLabel;
    ppDBText140: TppDBText;
    ppLabel229: TppLabel;
    ppDBText141: TppDBText;
    ppLabel230: TppLabel;
    ppDBText142: TppDBText;
    ppDBText146: TppDBText;
    ppShape139: TppShape;
    ppLabel235: TppLabel;
    ppLabel236: TppLabel;
    ppDBText147: TppDBText;
    ppLabel237: TppLabel;
    ppDBText148: TppDBText;
    ppLabel238: TppLabel;
    ppDBText149: TppDBText;
    ppLabel239: TppLabel;
    ppDBText150: TppDBText;
    ppLabel240: TppLabel;
    ppDBText151: TppDBText;
    TRelSaidaSinteticoCONSUMO_MN_TOTAL: TFloatField;
    TRelSaidaSinteticoCONSUMO_MS_TOTAL: TFloatField;
    ppLabel241: TppLabel;
    ppDBText152: TppDBText;
    ppLabel242: TppLabel;
    ppDBText153: TppDBText;
    ppLabel243: TppLabel;
    ppLabel244: TppLabel;
    ppLabel245: TppLabel;
    TRelSaidaSinteticoEFI_BIOLOGICA: TFloatField;
    ppDBText154: TppDBText;
    ppShape140: TppShape;
    ppLabel246: TppLabel;
    ppLabel248: TppLabel;
    ppDBText155: TppDBText;
    ppLabel249: TppLabel;
    ppDBText156: TppDBText;
    ppLabel250: TppLabel;
    ppDBText157: TppDBText;
    ppLabel251: TppLabel;
    ppDBText158: TppDBText;
    ppLabel252: TppLabel;
    ppDBText159: TppDBText;
    ppLabel253: TppLabel;
    ppDBText160: TppDBText;
    ppLabel254: TppLabel;
    ppDBText161: TppDBText;
    ppLabel255: TppLabel;
    ppLabel256: TppLabel;
    ppLabel257: TppLabel;
    ppDBText162: TppDBText;
    ppDBText163: TppDBText;
    ppDBText164: TppDBText;
    ppLabel247: TppLabel;
    ppDBText165: TppDBText;
    ppLabel258: TppLabel;
    ppDBText166: TppDBText;
    ppLabel259: TppLabel;
    ppDBText167: TppDBText;
    ppLabel260: TppLabel;
    ppDBText168: TppDBText;
    TRelSaidaSinteticoCUSTODIARIOTOTAL: TFloatField;
    TRelSaidaSinteticoDIAS_CONF: TLargeintField;
    ppLabel261: TppLabel;
    ppDBText169: TppDBText;
    TRelSaidaSinteticoEFICIENCIA_BIO: TFloatField;
    TRelSaidaSinteticoCONSUMO_MS_PV: TFloatField;
    TRelSaidaSinteticoCONVERSAO_ALIMENTAR: TFloatField;
    TRelSaidaSinteticoEFICIENCIA_ALIMENTAR: TFloatField;
    ppDBText170: TppDBText;
    ppDBText171: TppDBText;
    ppDBText172: TppDBText;
    ppLabel262: TppLabel;
    ppLabel231: TppLabel;
    ppDBText143: TppDBText;
    ppLabel232: TppLabel;
    ppShape138: TppShape;
    ppShape143: TppShape;
    ppShape144: TppShape;
    ppShape145: TppShape;
    ppShape146: TppShape;
    ppShape147: TppShape;
    ppShape148: TppShape;
    ppShape149: TppShape;
    ppShape150: TppShape;
    ppShape151: TppShape;
    ppShape152: TppShape;
    ppShape153: TppShape;
    ppShape154: TppShape;
    ppShape155: TppShape;
    ppShape156: TppShape;
    ppShape157: TppShape;
    ppShape158: TppShape;
    ppShape159: TppShape;
    ppShape160: TppShape;
    ppShape161: TppShape;
    ppShape162: TppShape;
    ppShape163: TppShape;
    ppShape164: TppShape;
    ppShape165: TppShape;
    ppShape166: TppShape;
    ppShape167: TppShape;
    ppShape168: TppShape;
    ppShape169: TppShape;
    ppShape170: TppShape;
    ppShape171: TppShape;
    ppShape172: TppShape;
    ppShape173: TppShape;
    ppShape174: TppShape;
    ppShape175: TppShape;
    ppShape176: TppShape;
    ppShape177: TppShape;
    ppShape178: TppShape;
    ppShape179: TppShape;
    ppShape180: TppShape;
    ppShape181: TppShape;
    ppShape182: TppShape;
    ppShape183: TppShape;
    ppShape184: TppShape;
    ppShape185: TppShape;
    ppShape186: TppShape;
    ppShape187: TppShape;
    ppShape188: TppShape;
    ppShape189: TppShape;
    ppShape190: TppShape;
    ppShape191: TppShape;
    ppShape192: TppShape;
    ppShape193: TppShape;
    ppShape194: TppShape;
    ppShape195: TppShape;
    ppShape141: TppShape;
    ppShape142: TppShape;
    ppShape196: TppShape;
    ppShape197: TppShape;
    ppShape198: TppShape;
    ppShape199: TppShape;
    ppShape200: TppShape;
    ppShape201: TppShape;
    ppShape202: TppShape;
    ppShape203: TppShape;
    ppShape204: TppShape;
    ppShape205: TppShape;
    ppShape206: TppShape;
    ppShape207: TppShape;
    ppShape208: TppShape;
    ppShape209: TppShape;
    ppShape210: TppShape;
    ppShape211: TppShape;
    ppShape212: TppShape;
    ppShape213: TppShape;
    ppShape214: TppShape;
    ppShape215: TppShape;
    ppShape216: TppShape;
    ppShape217: TppShape;
    ppShape218: TppShape;
    ppShape219: TppShape;
    ppShape220: TppShape;
    ppShape221: TppShape;
    ppShape222: TppShape;
    EstoqueAtual: TFDQuery;
    EstoqueAtualALIMENTO: TStringField;
    EstoqueAtualMS: TFMTBCDField;
    EstoqueAtualENTRADA: TFMTBCDField;
    EstoqueAtualSAIDAIND: TFMTBCDField;
    EstoqueAtualSAIDAFAB: TBCDField;
    EstoqueAtualVALORTOTAL: TFMTBCDField;
    EstoqueAtualVALORKG: TFloatField;
    EstoqueAtualSALDO: TBCDField;
    EstoqueAtualVALORMNTON: TFMTBCDField;
    EstoqueAtualVALORMSTON: TFMTBCDField;
    dsEstoqueAtual: TDataSource;
    ppRepEstoqueAtual: TppReport;
    ppHeaderBand19: TppHeaderBand;
    ppImage21: TppImage;
    ppImgCliEstoqueAtual: TppImage;
    ppLine42: TppLine;
    ppLabel215: TppLabel;
    ppDetailBand19: TppDetailBand;
    ppFooterBand19: TppFooterBand;
    ppLabel233: TppLabel;
    ppSystemVariable37: TppSystemVariable;
    ppSystemVariable38: TppSystemVariable;
    ppDesignLayers19: TppDesignLayers;
    ppDesignLayer19: TppDesignLayer;
    ppParameterList19: TppParameterList;
    ppDBEstoqueAtual: TppDBPipeline;
    ppShape244: TppShape;
    ppLabel263: TppLabel;
    ppShape223: TppShape;
    ppLabel234: TppLabel;
    ppShape224: TppShape;
    ppLabel264: TppLabel;
    ppShape225: TppShape;
    ppLabel265: TppLabel;
    ppShape226: TppShape;
    ppLabel266: TppLabel;
    ppShape227: TppShape;
    ppLabel267: TppLabel;
    ppShape228: TppShape;
    ppLabel268: TppLabel;
    ppDBText144: TppDBText;
    ppDBText145: TppDBText;
    ppDBText173: TppDBText;
    ppDBText178: TppDBText;
    ppDBText179: TppDBText;
    ppDBText180: TppDBText;
    EstoqueAtualTOTALSAIDA: TBCDField;
    ppDBText174: TppDBText;
    ppLine43: TppLine;
    EstoqueExtrato: TFDQuery;
    dsEstoqueExtrato: TDataSource;
    ppRepEstoqueExtrato: TppReport;
    ppHeaderBand20: TppHeaderBand;
    ppImage22: TppImage;
    ppImgEstoqueExtrato: TppImage;
    ppLine45: TppLine;
    ppLabel269: TppLabel;
    ppDetailBand20: TppDetailBand;
    ppLine46: TppLine;
    ppFooterBand20: TppFooterBand;
    ppLabel277: TppLabel;
    ppSystemVariable39: TppSystemVariable;
    ppSystemVariable40: TppSystemVariable;
    ppDesignLayers20: TppDesignLayers;
    ppDesignLayer20: TppDesignLayer;
    ppParameterList20: TppParameterList;
    ppDBEstoqueExtrato: TppDBPipeline;
    EstoqueExtratoR_DATA: TDateField;
    EstoqueExtratoR_ALIMENTO: TStringField;
    EstoqueExtratoR_ESTOQUE_INICAL: TFloatField;
    EstoqueExtratoR_ENTRADA: TFloatField;
    EstoqueExtratoR_SAIDA_AVULSO: TFloatField;
    EstoqueExtratoR_SAIDA_FABRICA: TFloatField;
    EstoqueExtratoR_TOTAL_SAIDA: TFloatField;
    EstoqueExtratoR_SALDO_DIA: TFloatField;
    ppGroup13: TppGroup;
    ppGroupHeaderBand13: TppGroupHeaderBand;
    ppGroupFooterBand13: TppGroupFooterBand;
    ppShape229: TppShape;
    ppShape230: TppShape;
    ppLabel271: TppLabel;
    ppDBText181: TppDBText;
    ppShape231: TppShape;
    ppLabel270: TppLabel;
    ppDBText175: TppDBText;
    ppDBText176: TppDBText;
    ppShape232: TppShape;
    ppLabel272: TppLabel;
    ppShape233: TppShape;
    ppLabel273: TppLabel;
    ppShape234: TppShape;
    ppLabel274: TppLabel;
    ppShape235: TppShape;
    ppLabel275: TppLabel;
    ppShape236: TppShape;
    ppLabel276: TppLabel;
    ppDBText177: TppDBText;
    ppDBText182: TppDBText;
    ppDBText183: TppDBText;
    ppDBText184: TppDBText;
    ppDBText185: TppDBText;
    ppSummaryBand14: TppSummaryBand;
    ppDBCalc60: TppDBCalc;
    ppDBCalc61: TppDBCalc;
    ppShape237: TppShape;
    ppShape238: TppShape;
    ppDBCalc62: TppDBCalc;
    ppShape239: TppShape;
    ppDBCalc63: TppDBCalc;
    ppShape240: TppShape;
    ppDBCalc64: TppDBCalc;
    ppShape241: TppShape;
    ppDBCalc65: TppDBCalc;
    ppShape242: TppShape;
    ppRepRelAnimalVeiculo: TppReport;
    ppHeaderBand21: TppHeaderBand;
    ppImage23: TppImage;
    ppLine47: TppLine;
    ppLabel278: TppLabel;
    ppShape246: TppShape;
    ppDetailBand21: TppDetailBand;
    ppLine48: TppLine;
    ppFooterBand21: TppFooterBand;
    ppLine49: TppLine;
    ppLabel282: TppLabel;
    ppSystemVariable41: TppSystemVariable;
    ppSystemVariable42: TppSystemVariable;
    ppSummaryBand15: TppSummaryBand;
    ppDesignLayers21: TppDesignLayers;
    ppDesignLayer21: TppDesignLayer;
    ppParameterList21: TppParameterList;
    qryRelAnimalVeiculo: TFDQuery;
    dsRelAnimalVeiculo: TDataSource;
    ppDBRelAnimalVeiculo: TppDBPipeline;
    qryRelAnimalVeiculoORIGEM: TStringField;
    qryRelAnimalVeiculoDESTINO: TStringField;
    qryRelAnimalVeiculoNOME: TStringField;
    qryRelAnimalVeiculoPLACA: TStringField;
    qryRelAnimalVeiculoPLACA_CR: TStringField;
    qryRelAnimalVeiculoMOTORISTA: TStringField;
    qryRelAnimalVeiculoTIPO: TStringField;
    qryRelAnimalVeiculoCAPACIDADE: TIntegerField;
    qryRelAnimalVeiculoIDENTIFICACAO_1: TStringField;
    qryRelAnimalVeiculoIDENTIFICACAO_2: TStringField;
    ppLabel279: TppLabel;
    ppLabel280: TppLabel;
    ppLabel281: TppLabel;
    ppLabel283: TppLabel;
    ppLabel284: TppLabel;
    ppLabel285: TppLabel;
    ppLabel286: TppLabel;
    ppLabel287: TppLabel;
    ppDBText188: TppDBText;
    ppDBText189: TppDBText;
    ppDBText190: TppDBText;
    ppDBText191: TppDBText;
    ppDBText192: TppDBText;
    ppDBText193: TppDBText;
    ppDBText194: TppDBText;
    ppDBText195: TppDBText;
    ppShape243: TppShape;
    ppLabel288: TppLabel;
    ppLabel289: TppLabel;
    ppDBText186: TppDBText;
    ppDBText187: TppDBText;
    ppColumnHeaderBand2: TppColumnHeaderBand;
    ppColumnFooterBand2: TppColumnFooterBand;
    ppShape247: TppShape;
    ppDBCalc66: TppDBCalc;
    ppLabel290: TppLabel;
    ppLine50: TppLine;
    ppLine51: TppLine;
    ppLabel291: TppLabel;
    ppLabel292: TppLabel;
    qryRelAnimalVeiculoCLIENTE: TStringField;
    ppLabel293: TppLabel;
    ppDBText196: TppDBText;
    TRelSaidaNUM_CONTRATO: TStringField;
    TRelSaidaCATEGORIA: TStringField;
    TRelSaidaRACA: TStringField;
    ppLabel294: TppLabel;
    ppDBText197: TppDBText;
    ppLabel295: TppLabel;
    qryRelMorte: TFDQuery;
    qryRelMorteDATA_MORTE: TDateField;
    qryRelMorteIDENTIFICACAO: TStringField;
    qryRelMorteRACA: TStringField;
    qryRelMorteCATEGORIA: TStringField;
    qryRelMorteDATA_ENTRADA: TDateField;
    qryRelMorteMOTIVO: TStringField;
    qryRelMorteCUSTO_COMPRA: TFloatField;
    qryRelMorteCUSTO_ALIMENTAR: TFloatField;
    qryRelMorteCUSTO_SANIDADE: TFloatField;
    qryRelMorteCUSTO_FIXO: TFloatField;
    qryRelMorteCUSTO_TOTAL: TFMTBCDField;
    qryRelMorteLOCAL_ATUAL: TStringField;
    ppLabel296: TppLabel;
    ppLabel297: TppLabel;
    ppLabel298: TppLabel;
    ppDBText198: TppDBText;
    ppDBText199: TppDBText;
    ppDBText200: TppDBText;
    ppLabel299: TppLabel;
    ppDBText201: TppDBText;
    qryRelMortePRODUTOR: TStringField;
    FarmacoSaldo: TFDQuery;
    dsFarmacoSaldo: TDataSource;
    ppDBFarmacoSaldo: TppDBPipeline;
    FarmacoSaldoNOME_FARMACO: TStringField;
    FarmacoSaldoTOTAL_ENTRADA_ML: TFloatField;
    FarmacoSaldoTOTAL_ENTRADA_UN: TFloatField;
    FarmacoSaldoTOTAL_SAIDA_ML: TFloatField;
    FarmacoSaldoTOTAL_SAIDA_UN: TFloatField;
    FarmacoSaldoSALDO_ATUAL_ML: TFloatField;
    FarmacoSaldoSALDO_ATUAL_UN: TFloatField;
    FarmacoSaldoVALOR_MEDIO_UN: TFloatField;
    FarmacoSaldoVALOR_MEDIO_ML: TFMTBCDField;
    ppRepFarmacoSaldo: TppReport;
    ppHeaderBand22: TppHeaderBand;
    ppImage24: TppImage;
    ppImage25: TppImage;
    ppLine52: TppLine;
    ppLabel300: TppLabel;
    ppShape245: TppShape;
    ppLabel301: TppLabel;
    ppShape249: TppShape;
    ppLabel303: TppLabel;
    ppShape250: TppShape;
    ppLabel304: TppLabel;
    ppShape251: TppShape;
    ppLabel305: TppLabel;
    ppShape252: TppShape;
    ppLabel306: TppLabel;
    ppShape253: TppShape;
    ppLabel307: TppLabel;
    ppDetailBand22: TppDetailBand;
    ppDBText202: TppDBText;
    ppDBText204: TppDBText;
    ppDBText205: TppDBText;
    ppDBText206: TppDBText;
    ppDBText207: TppDBText;
    ppLine53: TppLine;
    ppDBText208: TppDBText;
    ppFooterBand22: TppFooterBand;
    ppLabel308: TppLabel;
    ppSystemVariable43: TppSystemVariable;
    ppSystemVariable44: TppSystemVariable;
    ppSummaryBand16: TppSummaryBand;
    ppDesignLayers22: TppDesignLayers;
    ppDesignLayer22: TppDesignLayer;
    ppParameterList22: TppParameterList;
    ppShape248: TppShape;
    ppLabel302: TppLabel;
    ppDBText203: TppDBText;
    qryRelMorteCHIP: TStringField;
    qryRelMorteSISBOV: TStringField;
    qryRelMorteCONTRATO: TStringField;
    qryRelMortePESO_ENTRADA: TFMTBCDField;
    ppShape254: TppShape;
    ppDBText209: TppDBText;
    ppShape255: TppShape;
    ppLabel310: TppLabel;
    ppDBText210: TppDBText;
    ppLabel309: TppLabel;
    TRelSaidaDATA_ULTIMO_PESO: TDateField;
    TRelSaidaULTIMO_PESO: TFloatField;
    ppRepRelSaidaInd: TppReport;
    ppParameterList23: TppParameterList;
    TRelSaidaSinteticoPRODUTORORIGEM: TStringField;
    TRelSaidaSinteticoPROPRIEDADEORIGEM: TStringField;
    TRelSaidaSinteticoDATA_ENT_CONF: TDateField;
    ppHeaderBand23: TppHeaderBand;
    ppShape320: TppShape;
    ppLabel313: TppLabel;
    ppLabel314: TppLabel;
    ppLabel315: TppLabel;
    ppDBText211: TppDBText;
    ppDBText212: TppDBText;
    ppLabel316: TppLabel;
    ppDBText213: TppDBText;
    ppDBText215: TppDBText;
    ppLabel318: TppLabel;
    ppLabel319: TppLabel;
    ppLabel320: TppLabel;
    ppLabel321: TppLabel;
    ppLabel322: TppLabel;
    ppLabel323: TppLabel;
    ppDBText217: TppDBText;
    ppDBText218: TppDBText;
    ppDBText219: TppDBText;
    ppDBText220: TppDBText;
    ppDBText221: TppDBText;
    ppDBText222: TppDBText;
    ppLabel325: TppLabel;
    ppDBText223: TppDBText;
    ppLabel326: TppLabel;
    ppDBText224: TppDBText;
    ppLabel327: TppLabel;
    ppDBText225: TppDBText;
    ppLabel328: TppLabel;
    ppDBText226: TppDBText;
    ppLabel329: TppLabel;
    ppDBText227: TppDBText;
    ppLabel331: TppLabel;
    ppDBText229: TppDBText;
    ppDBText230: TppDBText;
    ppLabel334: TppLabel;
    ppDBText232: TppDBText;
    ppLabel335: TppLabel;
    ppDBText233: TppDBText;
    ppLabel336: TppLabel;
    ppLabel337: TppLabel;
    ppDBText235: TppDBText;
    ppLabel338: TppLabel;
    ppDBText236: TppDBText;
    ppLabel341: TppLabel;
    ppDBText239: TppDBText;
    ppLabel342: TppLabel;
    ppDBText240: TppDBText;
    ppLabel343: TppLabel;
    ppDBText241: TppDBText;
    ppLabel344: TppLabel;
    ppLabel345: TppLabel;
    ppLabel346: TppLabel;
    ppDBText242: TppDBText;
    ppShape324: TppShape;
    ppLabel347: TppLabel;
    ppLabel348: TppLabel;
    ppDBText243: TppDBText;
    ppLabel349: TppLabel;
    ppDBText244: TppDBText;
    ppLabel350: TppLabel;
    ppDBText245: TppDBText;
    ppLabel351: TppLabel;
    ppDBText246: TppDBText;
    ppLabel352: TppLabel;
    ppDBText247: TppDBText;
    ppLabel353: TppLabel;
    ppDBText248: TppDBText;
    ppLabel354: TppLabel;
    ppDBText249: TppDBText;
    ppLabel355: TppLabel;
    ppDBText250: TppDBText;
    ppLabel356: TppLabel;
    ppDBText251: TppDBText;
    ppLabel357: TppLabel;
    ppDBText252: TppDBText;
    ppLabel358: TppLabel;
    ppDBText253: TppDBText;
    ppLabel359: TppLabel;
    ppDBText254: TppDBText;
    ppLabel360: TppLabel;
    ppDBText255: TppDBText;
    ppDBText256: TppDBText;
    ppDBText257: TppDBText;
    ppDBText258: TppDBText;
    ppLabel365: TppLabel;
    ppDBText260: TppDBText;
    ppLabel366: TppLabel;
    ppDBText261: TppDBText;
    ppShape343: TppShape;
    ppLabel367: TppLabel;
    ppLabel368: TppLabel;
    ppDBText262: TppDBText;
    ppDBText263: TppDBText;
    ppLabel369: TppLabel;
    ppLabel364: TppLabel;
    ppDBText234: TppDBText;
    ppLabel361: TppLabel;
    ppDBText214: TppDBText;
    ppLabel317: TppLabel;
    ppDBText216: TppDBText;
    ppLabel362: TppLabel;
    ppDBText259: TppDBText;
    ppLabel363: TppLabel;
    ppDetailBand23: TppDetailBand;
    ppFooterBand23: TppFooterBand;
    ppLine54: TppLine;
    ppLabel312: TppLabel;
    ppSystemVariable45: TppSystemVariable;
    ppSystemVariable46: TppSystemVariable;
    ppSummaryBand17: TppSummaryBand;
    ppDesignLayers23: TppDesignLayers;
    ppDesignLayer23: TppDesignLayer;
    TRelSaidaSinteticoVALOR_COMPRA_ARR: TFloatField;
    TRelSaidaSinteticoVALOR_TOTAL_COMPRA_ARR: TFloatField;
    TRelSaidaSinteticoGMD_DIAS_CONF: TFloatField;
    TRelSaidaSinteticoGMD_DIAS_ALIMNTAR: TFloatField;
    TRelSaidaSinteticoGMD_DIAS_TOTAL: TFloatField;
    TRelSaidaSinteticoGMD_RC: TFloatField;
    TRelSaidaSinteticoGTP_ARROB_P_CONF: TFloatField;
    TRelSaidaSinteticoGTP_ARROB_P_ENT: TFloatField;
    TRelSaidaSinteticoPESO_CARCACA_PROJ: TFloatField;
    TRelSaidaSinteticoGMD_PROJ: TFloatField;
    TRelSaidaSinteticoGTP_PROJ: TFloatField;
    ppLabel324: TppLabel;
    ppDBText264: TppDBText;
    ppLabel370: TppLabel;
    ppDBText265: TppDBText;
    ppLabel371: TppLabel;
    ppDBText266: TppDBText;
    ppDBText267: TppDBText;
    ppLabel372: TppLabel;
    ppLabel332: TppLabel;
    ppLabel373: TppLabel;
    ppDBText268: TppDBText;
    ppLabel330: TppLabel;
    ppDBText228: TppDBText;
    ppLabel374: TppLabel;
    ppDBText269: TppDBText;
    ppLabel333: TppLabel;
    ppDBText231: TppDBText;
    ppLabel375: TppLabel;
    ppDBText270: TppDBText;
    ppLine55: TppLine;
    TRelSaidaSinteticoCUSTO_DIARIO_D_CONF: TFloatField;
    TRelSaidaSinteticoCUSTO_DIARIO_D_ALIMENTAR: TFloatField;
    TRelSaidaSinteticoCUSTO_PRODUCAO: TFloatField;
    TRelSaidaSinteticoCUSTO_ARROB_REAL: TFloatField;
    TRelSaidaSinteticoVALOR_VENDA: TFloatField;
    TRelSaidaSinteticoVALOR_ARROB_VENDA: TFloatField;
    TRelSaidaSinteticoLUCRO_LIQUI: TFloatField;
    ppLabel339: TppLabel;
    ppDBText237: TppDBText;
    ppLabel340: TppLabel;
    ppDBText238: TppDBText;
    ppLabel376: TppLabel;
    ppDBText271: TppDBText;
    ppLabel377: TppLabel;
    ppDBText272: TppDBText;
    ppLabel378: TppLabel;
    ppDBText273: TppDBText;
    ppLabel379: TppLabel;
    ppDBText274: TppDBText;
    ppLabel380: TppLabel;
    ppDBText275: TppDBText;
    TRelSaidaSinteticoCUSTO_DIARIO_D_TOTAL: TFloatField;
    TRelSaidaSinteticoCUSTO_DIARIO_D_CONF_TOTAL: TFloatField;
    TRelSaidaSinteticoCUSTO_DIARIO_D_ALIMENTAR_TOTAL: TFloatField;
    TRelSaidaSinteticoCUSTO_PRODUCAO_TOTAL: TFloatField;
    TRelSaidaSinteticoCUSTO_ARROB_REAL_TOTAL: TFloatField;
    TRelSaidaSinteticoVALOR_VENDA_TOTAL: TFloatField;
    TRelSaidaSinteticoVALOR_ARROB_VENDA_TOTAL: TFloatField;
    TRelSaidaSinteticoLUCRO_LIQUI_TOTAL: TFloatField;
    ppLabel381: TppLabel;
    ppDBText276: TppDBText;
    ppLabel382: TppLabel;
    ppDBText277: TppDBText;
    ppLabel383: TppLabel;
    ppDBText278: TppDBText;
    ppLabel384: TppLabel;
    ppDBText279: TppDBText;
    ppLabel385: TppLabel;
    ppDBText280: TppDBText;
    ppLabel386: TppLabel;
    ppDBText281: TppDBText;
    ppLabel387: TppLabel;
    ppDBText282: TppDBText;
    ppLabel388: TppLabel;
    ppDBText283: TppDBText;
    ppLabel389: TppLabel;
    ppDBText284: TppDBText;
    TRelSaidaSinteticoDIAS_CONF_TOTAL: TLargeintField;
    TRelSaidaSinteticoDIAS_ALIMENTAR_TOTAL: TLargeintField;
    ppDBText285: TppDBText;
    ppLabel390: TppLabel;
    ppLabel391: TppLabel;
    ppDBText286: TppDBText;
    ppLabel311: TppLabel;
    procedure ppHeaderBand1BeforePrint(Sender: TObject);
    procedure ppDetailBand1BeforePrint(Sender: TObject);
    procedure ppDetailBand4AfterGenerateLastDetail(Sender: TObject);
    procedure ppHeaderBand4BeforePrint(Sender: TObject);
    procedure ppHeaderBand3BeforePrint(Sender: TObject);
    procedure ppHeaderBand5BeforePrint(Sender: TObject);
    procedure ppHeaderBand12BeforeGenerate(Sender: TObject);
    procedure ppGroupHeaderBand12BeforePrint(Sender: TObject);
    procedure ppHeaderBand16BeforePrint(Sender: TObject);
    procedure ppHeaderBand19BeforePrint(Sender: TObject);
    procedure ppHeaderBand20BeforePrint(Sender: TObject);
    procedure ppRepRelAnimalVeiculoPreviewFormClose(Sender: TObject);
  private
    { Private declarations }
  public
    Procedure RelEstoquePrevisao;
    procedure AbreMapaGado(idPropriedade:string);
    procedure RelRelacaoEntradaAnimal(idFazenda,DataIni,DataFim,vFiltro:string);
    procedure AbreDiariasOcupacao(DataIni,DataFim:TDate;vFiltro:string);
    procedure AbreDiariasOcupacaoSexo(DataIni, DataFim: TDate; vFiltro: string);
    procedure AbreDiariasOcupacaoSexoSumario(DataIni, DataFim: TDate; vFiltro: string);
    procedure AbreDiariasOcupacaoGrafico;
    procedure AbreGraficoConsumo(idPasto,DataIni,DataFim:string);
    function  GeraGraficoConsumo(DataIni, DataFim: string):integer;
    procedure AbreEraEmbarque(idLoteSaida,idVeiculo:string);
    procedure AbreRelAnimaisVeiculo(idLoteSaida,idVeiculo:string);
    procedure AbreEraEmbarquels(idLoteSaida: string);
    procedure AbreHistObsManejo(Filtro:string);
    procedure AbreRelAnimaisAtivosRebanho;
    procedure AbreRelEraAnimais(idLocal,Sexo:string);

    procedure AbrirHistMovRebanho(vFiltro:string);

    procedure GeraRelSaida(LoteSaida:string);
    procedure AbreRelSaida(vFiltro:string);
    procedure AbreRelMorte(vDataDe,vDataAte,vFiltro:string);
    procedure AbreRelSaidaSintetico(vFiltro:string);
    procedure AbreEstoqueAtual(vFiltro:string);
    procedure AbreEstoqueExtrato(IN_DATA_INICIO,IN_DATA_FIM,IN_ALIMENTO,IN_TIPO:string);
    procedure AbreRelSaidaSinteticoInd(vFiltro: string);

  end;

var
  SerRel: TSerRel;

implementation

{%CLASSGROUP 'FMX.Controls.TControl'}

{$R *.dfm}

{ TDataModule1 }
uses UServiceDB, UPrincipal;
procedure TSerRel.AbreDiariasOcupacao(DataIni, DataFim: TDate; vFiltro: string);
var
 vDataIni,vDataFim:string;
begin
 vDataIni := FormatDateTime('mm/dd/yyyy',DataIni).QuotedString;
 vDataFim := FormatDateTime('mm/dd/yyyy',DataFim).QuotedString;
 with qryTmpExtratoMov,qryTmpExtratoMov.SQL do
 begin
   Clear;
   Add('SELECT');
   Add('C.CODIGO PastoCurral,');
   Add('ID_LOCAL,');
   Add('COUNT(*) dias,');
   Add('sum(SALDO_FINAL) DiariasOcupacao,');
   Add('sum(SALDO_FINAL)/COUNT(*) DiariasMedias');
   Add('FROM TMP_EXTRATO_ANIMAIS');
   Add('JOIN CURRAIS C ON C.ID=ID_LOCAL');
   Add('WHERE SALDO_FINAL>0 AND DATA_DIA BETWEEN '+vDataIni+' AND '+vDataFim);
   Add('AND ID_FAZENDA='+serviceDB.vIdPropriedade);
   Add(vFiltro);
   Add('GROUP BY ID_LOCAL,C.CODIGO');
   Open;
 end;
end;

procedure TSerRel.AbreDiariasOcupacaoSexo(DataIni, DataFim: TDate; vFiltro: string);
var
 vDataIni,vDataFim:string;
begin
 vDataIni := FormatDateTime('mm/dd/yyyy',DataIni).QuotedString;
 vDataFim := FormatDateTime('mm/dd/yyyy',DataFim).QuotedString;
 with qryTmpExtratoMovSexo,qryTmpExtratoMovSexo.SQL do
 begin
   Clear;
   Add('SELECT');
   Add('C.CODIGO PastoCurral,');
   Add('TMP.SEXO,');
   Add('SUM(SALDO_FINAL) DiariasOcupacao,');
   Add('COUNT(*) dias,');
   Add('(SUM(SALDO_FINAL)/COUNT(*)) DiariasMedias');
   Add('FROM TMP_EXTRATO_ANIMAIS_SEXO TMP');
   Add('JOIN CURRAIS C ON C.ID=ID_LOCAL');
   Add('WHERE SALDO_FINAL>0 AND DATA_DIA BETWEEN '+vDataIni+' AND '+vDataFim);
   Add('AND ID_FAZENDA='+serviceDB.vIdPropriedade);
   Add(vFiltro);
   Add('GROUP BY TMP.SEXO,C.CODIGO');
   Add('ORDER BY C.CODIGO,TMP.SEXO');
   qryTmpExtratoMovSexo.SQL.Text;
   Open;

 end;
end;

procedure TSerRel.AbreDiariasOcupacaoSexoSumario(DataIni, DataFim: TDate;
  vFiltro: string);
var
 vDataIni,vDataFim:string;
begin
 vDataIni := FormatDateTime('mm/dd/yyyy',DataIni).QuotedString;
 vDataFim := FormatDateTime('mm/dd/yyyy',DataFim).QuotedString;
 with qryAux,qryAux.SQL do
 begin
   Clear;
   Add('SELECT');
   Add('TMP.SEXO,');
   Add('SUM(SALDO_FINAL) DiariasOcupacao,');
   Add('COUNT(*) dias,');
   Add('(SUM(SALDO_FINAL)/COUNT(*)) DiariasMedias');
   Add('FROM TMP_EXTRATO_ANIMAIS_SEXO TMP');
   Add('WHERE DATA_DIA BETWEEN '+vDataIni+' AND '+vDataFim);
   Add('AND ID_FAZENDA='+serviceDB.vIdPropriedade);
   Add(vFiltro);
   Add('GROUP BY TMP.SEXO');
   Add('HAVING SUM(SALDO_FINAL)>0');
   Open;
   while not qryAux.eof do
   begin
     if qryAux.FieldByName('SEXO').AsString='M' then
     begin
       ppLalblTotalMacho.Text   :=  qryAux.FieldByName('DiariasOcupacao').AsString;
     end;
     if qryAux.FieldByName('SEXO').AsString='F' then
     begin
       ppLalblTotalFemeas.Text  := qryAux.FieldByName('DiariasOcupacao').AsString;
     end;
     qryAux.Next;
   end;
 end;
end;

procedure TSerRel.AbreEraEmbarque(idLoteSaida, idVeiculo: string);
begin
 with qryRelEraEmbaque,qryRelEraEmbaque.SQL do
 begin
  Clear;
  Add('SELECT ID_LOTESAIDA,VEICULO,FAIXA Faixa,COUNT(*) Qtde FROM');
  Add('(SELECT');
  Add('ID_LOTESAIDA,');
  Add('VEICULO,');
  Add('CASE');
  Add('WHEN IDADE_MESES >=0 AND IDADE_MESES<=12 THEN ''0 A 12''');
  Add('WHEN IDADE_MESES >=13 AND IDADE_MESES<=24 THEN ''13 A 24''');
  Add('WHEN IDADE_MESES >=25 AND IDADE_MESES<=36 THEN ''25 A 36''');
  Add('WHEN IDADE_MESES >36  THEN ''MAIS 36''');
  Add('END FAIXA');
  Add('FROM');
  Add('(');
  Add('SELECT');
  Add('A.ID_LOTESAIDA,');
  Add('B.NOME VEICULO,');
  Add('datediff(MONTH,DATA_NASCIMENTO,CURRENT_TIMESTAMP) IDADE_MESES');
  Add('FROM ANIMAL A');
  Add('JOIN VEICULOS_EMBARQUE B ON A.ID_VEICULO_SAIDA=B.ID');
  Add('JOIN CATEGORIAS C ON C.ID=A.ID_CATEGORIA');
  Add('WHERE A.STATUS=2 AND A.ID_PROPRIEDADE='+serviceDB.vIdPropriedade);
  if idLoteSaida.Length>0 then
   Add('AND A.ID_LOTESAIDA='+idLoteSaida);
  if idVeiculo.Length>0 then
   Add('AND A.ID_VEICULO_SAIDA='+idVeiculo);
  Add(')X)Y');
  Add('GROUP BY ID_LOTESAIDA,FAIXA,VEICULO');
  Open;
 end;
end;

procedure TSerRel.AbreEraEmbarquels(idLoteSaida: string);
begin
 with qryRelEraEmbaquels,qryRelEraEmbaquels.SQL do
 begin
  Clear;
  Add('SELECT FAIXA Faixa,COUNT(*) Qtde FROM');
  Add('(SELECT');
  Add('CASE');
  Add(' WHEN IDADE_MESES >=0 AND IDADE_MESES<=12 THEN ''0 A 12''');
  Add(' WHEN IDADE_MESES >=13 AND IDADE_MESES<=24 THEN ''13 A 24''');
  Add(' WHEN IDADE_MESES >=25 AND IDADE_MESES<=36 THEN ''25 A 36''');
  Add(' WHEN IDADE_MESES >36  THEN ''MAIS 36''');
  Add('END FAIXA');
  Add('FROM');
  Add('(');
  Add('SELECT');
  Add('datediff(MONTH,DATA_NASCIMENTO,CURRENT_TIMESTAMP) IDADE_MESES');
  Add('FROM ANIMAL A');
  Add('JOIN CATEGORIAS C ON C.ID=A.ID_CATEGORIA');
  Add('WHERE A.STATUS=2 AND A.ID_PROPRIEDADE='+serviceDB.vIdPropriedade);
  if idLoteSaida.Length>0 then
   Add('AND A.ID_LOTESAIDA='+idLoteSaida);
  Add(')X)Y');
  Add('GROUP BY FAIXA');
  qryRelEraEmbaquels.SQL.Text;
  Open;
 end;
end;

procedure TSerRel.AbreEstoqueAtual(vFiltro: string);
begin
 with EstoqueAtual,EstoqueAtual.SQL do
 begin
   Clear;
   Add('SELECT');
   Add('y.*,');
   Add('  coalesce(SaidaInd.TOTAL_IND,0)SaidaInd,');
   Add('    coalesce(SaidafAB.TOTAL_FAB,0)SaidafAB,');
   Add('     (coalesce(SaidaInd.TOTAL_IND,0)+coalesce(SaidafAB.TOTAL_FAB,0)) TOTALSAIDA,');
   Add('     Entrada-(coalesce(SaidaInd.TOTAL_IND,0)+coalesce(SaidafAB.TOTAL_FAB,0)) Saldo,');
   Add('     (ValorToTal/(Entrada/1000)) ValorMNTon,');
   Add('     CASE');
   Add('       WHEN MS >0  THEN ((ValorToTal/(Entrada/1000))*100)/MS');
   Add('      ELSE');
   Add('       0');
   Add('      END ValorMSTon');
   Add('   from');
   Add('   (SELECT');
   Add('     a.id ID_ALIMENTO,');
   Add('    a.NOME Alimento,');
   Add('    AVG(a.MS) Ms,');
   Add('    SUM(e.PESO_FAZENDA) Entrada,');
   Add('    sum(e.VALOR_TOTRAL_NF) ValorToTal,');
   Add('    AVG(e.VALOR_KG_NF) ValorKG');
   Add('   FROM  ESTOQUE_MINERAL_ENTRADA e');
   Add('   JOIN ALIMENTO a ON a.ID=e.ID_ALIMENTO');
   Add('   WHERE e.STATUS =1 AND e.ID_MINERAL =0 AND e.id_propriedade=' +frmPrincipal.vIDPropriedadePropria);
   Add('   GROUP BY a.NOME,a.id)y');
   Add('   LEFT JOIN');
   Add('   (SELECT be.id_alimento,SUM(be.QTD_KG) TOTAL_IND');
   Add('    FROM BAIXA_ESTOQUE_INSUMO_IND be');
   Add('    WHERE STATUS=1 and be.id_propriedade=' +frmPrincipal.vIDPropriedadePropria);
   Add('    group by be.id_alimento)SaidaInd');
   Add('    on y.ID_ALIMENTO=SaidaInd.id_alimento');
   Add('   left JOIN');
   Add('   (SELECT FI.id_alimento, SUM(fi.KG_FABRICADO) TOTAL_FAB');
   Add('    FROM FABRICACAO_INSUMOS fi');
   Add('    JOIN fabricacao FA ON FA.id=FI.id_fabricacao');
   Add('    WHERE fi.STATUS=1 and FA.id_propriedade=' +frmPrincipal.vIDPropriedadePropria);
   Add('    GROUP BY id_alimento)SaidafAB');
   Add('    on y.ID_ALIMENTO=SaidafAB.id_alimento');
   Add('    UNION ALL');
   Add('   SELECT');
   Add('   y.*,');
   Add('    0 SaidaInd,');
   Add('    coalesce(SaidafAB.TOTAL_FAB,0)SaidafAB,');
   Add('     (coalesce(SaidafAB.TOTAL_FAB,0)) TOTALSAIDA,');
   Add('     Entrada-(coalesce(SaidafAB.TOTAL_FAB,0)) Saldo,');
   Add('     (ValorToTal/(Entrada/1000)) ValorMNTon,');
   Add('     CASE');
   Add('       WHEN MS >0  THEN ((ValorToTal/(Entrada/1000))*100)/MS');
   Add('      ELSE');
   Add('       0');
   Add('      END ValorMSTon');
   Add('   from');
   Add('   (SELECT');
   Add('     a.id ID_ALIMENTO,');
   Add('    a.NOME Alimento,');
   Add('    AVG(a.MS_TOTAL) Ms,');
   Add('    SUM(e.PESO_FAZENDA) Entrada,');
   Add('    sum(e.VALOR_TOTRAL_NF) ValorToTal,');
   Add('    AVG(e.VALOR_KG_NF) ValorKG');
   Add('   FROM  ESTOQUE_MINERAL_ENTRADA e');
   Add('   JOIN SUPLEMENTO_MINERAL a ON a.ID=e.ID_MINERAL');
   Add('   WHERE e.STATUS =1  AND e.id_propriedade=' +frmPrincipal.vIDPropriedadePropria);
   Add('   GROUP BY a.NOME,a.id)y');
   Add('   left JOIN');
   Add('   (SELECT FI.id_concentrado, SUM(fi.KG_FABRICADO) TOTAL_FAB');
   Add('    FROM FABRICACAO_INSUMOS fi');
   Add('    JOIN fabricacao FA ON FA.id=FI.id_fabricacao');
   Add('    WHERE fi.STATUS=1 and FA.id_propriedade=' +frmPrincipal.vIDPropriedadePropria);
   Add('    GROUP BY id_concentrado)SaidafAB');
   Add('    on y.ID_ALIMENTO=SaidafAB.id_concentrado');
   EstoqueAtual.SQL.Text;
   Open;
   ppRepEstoqueAtual.Print;
 end;
end;

procedure TSerRel.AbreEstoqueExtrato(IN_DATA_INICIO, IN_DATA_FIM,
  IN_ALIMENTO,IN_TIPO: string);
begin
 with EstoqueExtrato,EstoqueExtrato.SQL do
 begin
   Clear;
   Add('SELECT * FROM ESTOQUE_EXTRATO (');
   Add(frmPrincipal.vIDPropriedadePropria+',');
   Add(IN_DATA_INICIO+',');
   Add(IN_DATA_FIM+',');
   Add(IN_ALIMENTO+',');
   Add(IN_TIPO+')');
   Open;
 end;
end;

procedure TSerRel.AbreDiariasOcupacaoGrafico;
begin
 with qryDiariasGrafico,qryDiariasGrafico.SQL do
 begin
   Clear;
   Add('SELECT');
   Add('C.CODIGO "Label",');
   Add(' SUM(SALDO_FINAL) "Value",');
   Add(' COUNT(*) dias,');
   Add('(SUM(SALDO_FINAL)/COUNT(*)) DiariasMedias');
   Add('FROM TMP_EXTRATO_ANIMAIS');
   Add('JOIN CURRAIS C ON C.ID=ID_LOCAL');
   Add('WHERE DATA_DIA BETWEEN current_date-30 AND current_date');
   Add('AND ID_FAZENDA='+serviceDB.vIdPropriedade);
   Add('GROUP BY C.CODIGO');
   Add('HAVING SUM(SALDO_FINAL)>0');
   Open;
 end;
end;


function TSerRel.GeraGraficoConsumo(DataIni, DataFim: string):integer;
var
 vQryCurrai:TFDQuery;
begin
 vQryCurrai := TFDQuery.Create(nil);
 vQryCurrai.Connection := serviceDB.FCon;
 with qryAux,qryAux.SQL do
 begin
   Clear;
   Add('DELETE FROM TMP_GRAFICO_CONSUMO');
   ExecSQL;
 end;

 with vQryCurrai,vQryCurrai.SQL do
 begin
   Clear;
   Add('SELECT DISTINCT ID_PASTO FROM FORNECIMENTO');
   Add('WHERE DATA_FORNECIMENTO BETWEEN '+FormatDateTime('mm/dd/yyyy',strtodate(DataIni)).QuotedString);
   Add(' AND  '+FormatDateTime('mm/dd/yyyy',strtodate(DataFim)).QuotedString);
   Open;
   while not vQryCurrai.Eof do
   begin
     with qryAux,qryAux.SQL do
     begin
       Clear;
       Add('INSERT INTO TMP_GRAFICO_CONSUMO ');
       Add('SELECT NULL,DATA_CONSUMO,PASTO,CONSUMO,QTD_ANIMAIS,CONSUMO_CAB FROM SELECT_CONSUMO_DIA(');
       Add(vQryCurrai.FieldByName('ID_PASTO').AsString+','+FormatDateTime('mm/dd/yyyy',strtodate(DataIni)).QuotedString+',');
       Add(FormatDateTime('mm/dd/yyyy',strtodate(DataFim)).QuotedString+')');
       try
        ExecSQL;
       except
        on E : Exception do
         ShowMessage('Erro ao gerar Grafico:'+e.Message);
       end;
       vQryCurrai.Next;
      end;
   end;
 end;
 Result := vQryCurrai.RecordCount;
end;


procedure TSerRel.GeraRelSaida(LoteSaida: string);
begin
 with qryAux,qryAux.SQL do
 begin
   Clear;
   Add('DELETE FROM  ANIMAL_SAIDA WHERE LOTE_SAIDA='+LoteSaida);
   ExecSQL;

   Clear;
   Add('EXECUTE procedure PROC_CRIA_ANIMAL_SAIDA('+LoteSaida+')');
   ExecSQL;
 end;
end;

procedure TSerRel.AbreGraficoConsumo(idPasto, DataIni, DataFim: string);
begin
// with qryAux,qryAux.SQL do
// begin
//   Clear;
//   Add('DELETE FROM TMP_GRAFICO_CONSUMO');
//   ExecSQL;
//
//   Clear;
//   Add('INSERT INTO TMP_GRAFICO_CONSUMO ');
//   Add('SELECT NULL,DATA_CONSUMO,PASTO,CONSUMO,QTD_ANIMAIS,CONSUMO_CAB FROM SELECT_CONSUMO_DIA(');
//   Add(idPasto+','+FormatDateTime('mm/dd/yyyy',strtodate(DataIni)).QuotedString+',');
//   Add(FormatDateTime('mm/dd/yyyy',strtodate(DataFim)).QuotedString+')');
//   ExecSQL;
// end;

 TGraficoConsumoTabela.ResourceOptions.SilentMode := True;
 with TGraficoConsumoTabela,TGraficoConsumoTabela.SQL do
 begin
   Clear;
   Add('SELECT * FROM TMP_GRAFICO_CONSUMO A');
   Add('JOIN CURRAIS B ON A.PASTO=B.CODIGO AND B.ID_PROPRIEDADE='+serviceDB.vIdPropriedade);
   Add('WHERE B.ID='+idPasto);
   Add(' AND DATA_CONSUMO BETWEEN'+FormatDateTime('mm/dd/yyyy',strtodate(DataIni)).QuotedString+' AND ');
   Add(FormatDateTime('mm/dd/yyyy',strtodate(DataFim)).QuotedString);
   Add('ORDER BY DATA_CONSUMO');
   Open;
 end;


 TGraficoConsumo.ResourceOptions.SilentMode := True;
 with TGraficoConsumo,TGraficoConsumo.SQL do
 begin
   Clear;
   Add('SELECT DATA_CONSUMO "Label",REPLACE(CONSUMO_CAB,'','',''.'') "Value" FROM TMP_GRAFICO_CONSUMO A');
   Add('JOIN CURRAIS B ON A.PASTO=B.CODIGO AND B.ID_PROPRIEDADE='+serviceDB.vIdPropriedade);
   Add('WHERE B.ID='+idPasto);
   Add('AND DATA_CONSUMO BETWEEN'+FormatDateTime('mm/dd/yyyy',strtodate(DataIni)).QuotedString+' AND ');
   Add(FormatDateTime('mm/dd/yyyy',strtodate(DataFim)).QuotedString);
   Add('ORDER BY DATA_CONSUMO');
   Open;
 end;
end;

procedure TSerRel.AbreHistObsManejo(Filtro: string);
begin
 with qryRelHistObs,qryRelHistObs.SQL do
 begin
   Clear;
   Add('SELECT');
   Add(' A.*,');
   Add(' F.CODIGO Curral,');
   Add(' B.NOME RACA,');
   Add(' D.NOME CATEGORIA,');
   Add(' E.NOME REBANHO,');
   Add(' c."DATA" DataObs,');
   Add(' c.HORA HoraObs,');
   Add(' u.NAME UsuarioOBS,');
   Add(' C.OBSERVACAO obsHist');
   Add('FROM ANIMAL A');
   Add('JOIN CURRAIS F ON F.ID=A.ID_LOCAL');
   Add('JOIN RACA B ON A.ID_RACA=B.ID');
   Add('JOIN CATEGORIAS D ON D.ID=A.ID_CATEGORIA');
   Add('JOIN AUX_REBANHO E ON E.ID=A.ID_REBANHO');
   Add('JOIN HIST_OBS_ANIMAL C ON A.ID=C.ID_ANIMAL');
   Add('JOIN USERS u ON u.ID=c.ID_USUARIO');
   Add('WHERE A.ID_PROPRIEDADE='+serviceDB.vIdPropriedade);
   Add(Filtro);
   qryRelHistObs.SQL.Text;
   Open;
 end;
end;

procedure TSerRel.AbreMapaGado(idPropriedade: string);
begin
 with qryMapaGado,qryMapaGado.SQL do
 begin
   Clear;
   Add('SELECT');
   Add(' Pasto ,');
   Add(' QtdCab  ,');
   Add(' peso_estimado,');
   Add(' TRUNC(dias)dias,');
   Add(' UA,');
   Add(' peso_entrada,');
   Add(' ultimo_peso,');
   Add(' area_hectares,');
   Add(' CASE');
   Add('  WHEN (UA>0 AND area_hectares>0) then');
   Add('    (UA/area_hectares)');
   Add('   else');
   Add('    0');
   Add(' end UAH,');
   Add(' trunc(gpt/dias,3) gmd,');
   Add(' totalArroba,');
   Add(' (SELECT COUNT(*) Machos FROM ANIMAL a');
   Add(' JOIN CATEGORIAS ca ON CA.ID=A.ID_CATEGORIA');
   Add(' JOIN CURRAIS c ON c.ID=a.ID_LOCAL');
   Add(' WHERE A.STATUS=1 AND a.ID_PROPRIEDADE=:id_propriedade AND CA.SEXO=''M'' AND c.CODIGO=Pasto)Machos,');
   Add(' (SELECT COUNT(*) Femeas FROM ANIMAL a');
   Add(' JOIN CATEGORIAS ca ON CA.ID=A.ID_CATEGORIA');
   Add(' JOIN CURRAIS c ON c.ID=a.ID_LOCAL');
   Add(' WHERE A.STATUS=1 AND a.ID_PROPRIEDADE=:id_propriedade AND CA.SEXO=''F'' AND c.CODIGO=Pasto)Femeas');
   Add(' FROM');
   Add(' (select');
   Add('  Pasto,');
   Add('  (COUNT(*)*AVG(peso))/450 UA,');
   Add('  AVG(area_hectares)area_hectares,');
   Add('  COUNT(*) QtdCab,');
   Add(' AVG(peso_estimado) peso_estimado,');
   Add('  avg(dias)+1dias,');
   Add('  avg(gpt)gpt,');
   Add('  sum(arroba) totalArroba,');
   Add(' avg(peso_entrada)peso_entrada,');
   Add(' avg(ultimo_peso)ultimo_peso');
   Add(' from');
   Add(' (');
   Add(' select c.codigo Pasto,');
   Add(' a.peso_estimado,');
   Add(' a.peso_estimado peso,');
   Add(' C.area_hectares,');
   Add('cast(datediff(day from a.data_proc to current_timestamp)as DOUBLE PRECISION)  dias,');
   Add(' (a.peso_estimado-a.peso_entrada) gpt,');
   Add(' ((peso_estimado/2)/15) arroba,');
   Add(' a.peso_entrada,');
   Add(' a.ultimo_peso');
   Add(' from animal a');
   Add(' join currais c on c.id=a.id_local');
   Add(' where a.status=1 and a.id_propriedade=:id_propriedade)');
   Add(' GROUP BY Pasto)');
   ParamByName('id_propriedade').AsString := idPropriedade;
   Open;
   ppReportMapaGado.Print;
 end;
end;


procedure TSerRel.AbreRelAnimaisAtivosRebanho;
begin
 with qryRelRebanhoAtivos,qryRelRebanhoAtivos.SQL do
 begin
   Clear;
   Add('SELECT');
   Add(' r.NOME REBANHO,');
   Add(' c.CODIGO CURRAL,');
   Add(' CA.SEXO,');
   Add(' COUNT(*),');
   Add(' AVG(COALESCE(a.ULTIMO_PESO,PESO_ENTRADA)) media_ultima_pesagem,');
   Add(' MIN(A.DATA_PROC) PRIMEIRA_ENTRDA,');
   Add(' MAX(A.DATA_PROC) ULTIM_ENTRDA');
   Add('FROM ANIMAL a');
   Add('JOIN CURRAIS c ON c.id=a.ID_LOCAL');
   Add('JOIN CATEGORIAS CA ON CA.ID=A.ID_CATEGORIA');
   Add('JOIN AUX_REBANHO r ON a.ID_REBANHO=r.id');
   Add('WHERE a.STATUS=1 AND A.ID_PROPRIEDADE='+serviceDB.vIdPropriedade);
   Add('GROUP BY CA.SEXO,r.NOME,c.CODIGO');
   Open;
 end;
end;

procedure TSerRel.AbreRelAnimaisVeiculo(idLoteSaida, idVeiculo: string);
begin
 with qryRelAnimalVeiculo,qryRelAnimalVeiculo.SQL do
 begin
   Clear;
   Add('SELECT');
   Add('pro.NOME Origem,');
   Add(' prd.NOME Destino,');
   Add(' ve.NOME,');
   Add(' ve.PLACA,');
   Add(' ve.PLACA_CR,');
   Add(' ve.MOTORISTA,');
   Add(' ve.TIPO ,');
   Add(' ve.CAPACIDADE,');
   Add(' A.IDENTIFICACAO_1,');
   Add(' A.IDENTIFICACAO_2,');
   Add(' ve.Cliente');
   Add('FROM ANIMAL A');
   Add('JOIN LOTE_SAIDA L ON A.ID_LOTESAIDA=L.ID');
   Add('JOIN VEICULOS_EMBARQUE ve ON A.ID_VEICULO_SAIDA=ve.id');
   Add('JOIN PRODUTORES po ON po.id=L.ID_PRODUTOR_ORIGEM');
   Add('JOIN PROPRIEDADES pro ON pro.id=po.ID_PROPRIEDADE');
   Add('JOIN PRODUTORES pd ON pd.id=L.ID_PRODUTOR_DESTINO');
   Add('JOIN PROPRIEDADES prd ON prd.id=pd.ID_PROPRIEDADE');
   Add('WHERE ID_VEICULO_SAIDA=:ID_VEICULO_SAIDA');
   Add('AND L.ID=:ID_LS');
   ParamByName('ID_LS').AsString := idLoteSaida;
   ParamByName('ID_VEICULO_SAIDA').AsString := idVeiculo;
   Open;
 end;
end;

procedure TSerRel.AbreRelEraAnimais(idLocal, Sexo: string);
begin
  with qryRelEra,qryRelEra.SQL do
 begin
   Clear;
   Add('SELECT');
    Add('SEXO,');
   Add(' FAIXA,');
   Add(' COUNT(*) Qtde');
   Add('FROM');
   Add('(SELECT');
   Add('Y.SEXO,');
   Add(' CASE');
   Add('  WHEN y.ERA<=12 THEN');
   Add('   ''0 a 12''');
   Add('  WHEN (y.ERA>12 AND y.ERA<=24) THEN');
   Add('   ''13 a 24''');
   Add('  WHEN (y.ERA>24 AND y.ERA<=36) THEN');
   Add('   ''25 a 36''');
   Add('  WHEN (y.ERA>36) THEN');
   Add('   ''Mais 36''');
   Add(' END Faixa');
   Add('FROM');
   Add('(SELECT c.SEXO,ROUND((CURRENT_DATE-DATA_NASCIMENTO)/30.4167) ERA FROM ANIMAL a');
   Add('JOIN CATEGORIAS c ON c.ID=a.ID_CATEGORIA');
   Add('WHERE a.STATUS =1');
   if idLocal.Length>0 then
    Add('and a.ID_LOCAL='+idLocal);
   Add(')Y)W');
   if Sexo.Length>0 then
    Add('WHERE SEXO='+Sexo.QuotedString);
   Add('GROUP BY SEXO,FAIXA');
   Open;
 end;
end;

procedure TSerRel.AbreRelMorte(vDataDe,vDataAte,vFiltro: string);
begin
 with qryRelMorte,qryRelMorte.SQL do
 begin
   Clear;
   Add('SELECT * FROM RELATORIO_MORTE_ANIMAL('+vDataDe+','+vDataAte+')');
   Add('WHERE 1=1');
   Add(vFiltro);
   Open;
 end;
end;

procedure TSerRel.AbreRelSaida(vFiltro: string);
begin
 with TRelSaida,TRelSaida.SQL do
 begin
  Clear;
  Add('SELECT');
  Add('s.*, c.NOME Categoria,r.NOME Raca ,');
  Add(' cu.CODIGO Curral,');
  Add(' a.IDENTIFICACAO_1 Chip,');
  Add(' a.IDENTIFICACAO_2 SISBOV,');
  Add(' ar.NOME Rebanho,');
  Add(' p.NOME ProdutorOrigem,');
  Add(' p2.NOME PropriedadeOrigem,');
  Add(' p3.NOME ProdutorDestino,');
  Add(' p4.NOME PropriedadeDestino,');
  Add(' (SELECT COUNT(*) FROM ANIMAL_SAIDA WHERE LOTE_SAIDA= a.ID_LOTESAIDA) QTD_CAB_LOTE,');
  Add(' (SELECT SUM(PESO_CARCACA_REAL) FROM ANIMAL_SAIDA WHERE LOTE_SAIDA= a.ID_LOTESAIDA) TOTAL_CARCACA_LOTE,');
  Add(' (SELECT AVG(PESO_SAIDA) FROM ANIMAL_SAIDA WHERE LOTE_SAIDA= a.ID_LOTESAIDA) MEDIA_PESO_SAIDA_LOTE');
  Add('FROM ANIMAL_SAIDA s');
  Add('JOIN ANIMAL a  ON a.ID=s.ID_ANIMAL');
  Add('JOIN CATEGORIAS c ON C.ID=A.ID_CATEGORIA');
  Add('JOIN RACA r ON r.ID=a.ID_RACA');
  Add('JOIN CURRAIS cu ON cu.ID=a.ID_LOCAL');
  Add('JOIN AUX_REBANHO ar ON ar.ID=a.ID_REBANHO');
  Add('JOIN PRODUTORES p ON p.ID=a.ID_PRODUTOR');
  Add('JOIN PROPRIEDADES p2 ON p2.ID=a.ID_PROPRIEDADE');
  Add('JOIN LOTE_SAIDA ls ON ls.ID=a.ID_LOTESAIDA');
  Add('JOIN PRODUTORES p3 ON p3.ID = ls.ID_PRODUTOR_DESTINO');
  Add('JOIN PROPRIEDADES p4 ON p4.ID=ls.ID_DESTINO');
  Add('WHERE 1=1');
  Add(vFiltro);
  Open;
 end;
end;

procedure TSerRel.AbreRelSaidaSintetico(vFiltro: string);
begin
 with TRelSaidaSintetico,TRelSaidaSintetico.sql do
 begin
   Clear;
   Add('SELECT');
   Add('     Y.*,');
   Add('     CASE');
   Add('      WHEN GTP_REAL_ARROBA>0  THEN');
   Add('          CONSUMO_MS_KG_CAB_TOTAL/GTP_REAL_ARROBA');
   Add('         ELSE');
   Add('         0');
   Add('      END EFICIENCIA_BIO,');
   Add('      CASE');
   Add('        WHEN (PESO_SAIDA>0 AND PESO_ENT_CONF>0) THEN');
   Add('          ((CONSUMO_MS_KG_CAB_DIA*100)/((PESO_SAIDA+PESO_ENT_CONF)/2))');
   Add('        ELSE');
   Add('         0');
   Add('      END CONSUMO_MS_PV,');
   Add('      CASE');
   Add('        WHEN (GMD_TOTAL>0) THEN');
   Add('         (CONSUMO_MS_KG_CAB_DIA/GMD_TOTAL)');
   Add('        ELSE');
   Add('         0');
   Add('      END CONVERSAO_ALIMENTAR,');
   Add('      CASE');
   Add('        WHEN (CONSUMO_MS_KG_CAB_DIA>0) THEN');
   Add('         (GMD_TOTAL/ CONSUMO_MS_KG_CAB_DIA)');
   Add('        ELSE');
   Add('         0');
   Add('      END EFICIENCIA_ALIMENTAR');
   Add('   FROM');
   Add('   (SELECT');
   Add('    s.LOTE_SAIDA,');
   Add('    MAX(s.DATA_SAIDA)DATA_SAIDA,');
   Add('    min(DATA_ENT_CONF) DATA_ENT_CONF,');
   Add('    ar.NOME Rebanho,');
   Add('    p3.NOME ProdutorDestino,');
   Add('    p4.NOME PropriedadeDestino,');
   Add('    p.NOME ProdutorOrigem,');
   Add('    p2.NOME PropriedadeOrigem,');
   Add('    COUNT(*) QTD_CAB,');
   Add('    AVG(s.DIAS_CONF)DIAS_CONF,');
   Add('    ROUND(AVG(s.PESO_ENT_CONF),3)PESO_ENT_CONF,');
   Add('    ROUND(AVG(s.PESO_ENT_CONF_ARROB),3)PESO_ENT_CONF_ARROBA,');
   Add('    ROUND(AVG(s.PESO_SAIDA),3)PESO_SAIDA,');
   Add('    ROUND(AVG(s.PESO_SAIDA_ARROB),3)PESO_SAIDA_ARROBA,');
   Add('    ROUND(AVG(s.PESO_PROJ),3)PESO_PROJ,');
   Add('    ROUND((AVG(s.PESO_PROJ)/30),3)PESO_PROJ_ARROBA,');
   Add('    ROUND((MIN(s.PESO_SAIDA)),3)PESO_MIN_SAIDA,');
   Add('    ROUND((MIN(s.PESO_SAIDA) * (AVG(s.RC)/100))/15,3)PESO_MIN_ARROBA,');
   Add('    ROUND((MAX(s.PESO_SAIDA)),3)PESO_MAX_SAIDA,');
   Add('    ROUND((MAX(s.PESO_SAIDA)*(AVG(s.RC)/100))/15,3)PESO_MAX_ARROBA,');
   Add('    ROUND(AVG(s.GMD_DIAS_CONF),3)GMD_TOTAL,');
   Add('    ROUND((AVG(s.PESO_CARCACA_REAL)-(AVG(s.PESO_ENT_CONF)/2))/AVG(s.DIAS_CONF),3) GMD_TOTAL_ARROBA,');
   Add('    ROUND(AVG(s.GTP_REAL),3)GTP_REAL,');
   Add('    ROUND(AVG(s.PESO_SAIDA_ARROB)-AVG(s.PESO_ENT_CONF_ARROB),3)GTP_REAL_ARROBA,');
   Add('    ROUND(SUM(s.GTP_REAL),3)GTP_TOTAL,');
   Add('    ROUND((AVG(s.PESO_SAIDA_ARROB)-AVG(s.PESO_ENT_CONF_ARROB))*COUNT(*),3) GTP_TOTAL_ARROBA,');
   Add('    ROUND(AVG(s.PESO_CARCACA_REAL),3)PESO_CARCACA,');
   Add('    ROUND(AVG(ls.PESO_CARCACA_TOTAL),3)TOTAL_PESO_CARCACA,');
   Add('    ROUND(SUM(s.PESO_SAIDA_ARROB),3) ARROBA_TOTAL,');
   Add('    ROUND(SUM(s.PESO_SAIDA),3) PESO_SAIDA_TOTAL,     ');
   Add('    ROUND(COALESCE(AVG(s.RC),50),3)RC,');
   Add('    ROUND(AVG(s.CONSUMO_MN_KG_CAB_DIA),3)CONSUMO_MN_KG_CAB_DIA,');
   Add('    ROUND(AVG(s.CONSUMO_MS_KG_CAB_DIA),3)CONSUMO_MS_KG_CAB_DIA,');
   Add('    ROUND(AVG(s.CONSUMO_MN_KG_CAB_TOTAL),3)CONSUMO_MN_KG_CAB_TOTAL,');
   Add('    ROUND(AVG(s.CONSUMO_MS_KG_CAB_TOTAL),3)CONSUMO_MS_KG_CAB_TOTAL,');
   Add('    ROUND(SUM(s.CONSUMO_MN_KG_CAB_TOTAL),3)CONSUMO_MN_TOTAL,');
   Add('    ROUND(SUM(s.CONSUMO_MS_KG_CAB_TOTAL),3)CONSUMO_MS_TOTAL,');
   Add('    CASE');
   Add('      WHEN SUM(s.GMD_DIAS_CONF)>0 then');
   Add('       ROUND(SUM(s.CONSUMO_MS_KG_CAB_TOTAL)/SUM(s.GMD_DIAS_CONF),3)');
   Add('      ELSE');
   Add('       0');
   Add('     END CONVERSAO,');
   Add('     CASE');
   Add('      WHEN SUM(s.GTP_REAL)>0 then');
   Add('       ROUND(SUM(s.CONSUMO_MS_KG_CAB_TOTAL)/SUM(s.GTP_REAL),3)');
   Add('      ELSE');
   Add('       0');
   Add('     END EFI_BIOLOGICA,');
   Add('    ROUND(AVG(s.CUSTO_COMPRA),3)VALOR_COMPRA,');
   Add('    ROUND(SUM(s.CUSTO_COMPRA),3)VALOR_TOTAL_COMPRA,');
   Add('    ROUND(AVG(s.CUSTO_COMPRA)/AVG(s.PESO_ENT_CONF_ARROB),2)VALOR_COMPRA_ARR,');
   Add('    ROUND(SUM(s.CUSTO_COMPRA)/SUM(s.PESO_ENT_CONF_ARROB),2)VALOR_TOTAL_COMPRA_ARR,');
   Add('    ROUND(AVG(s.CUSTO_ALIMENTAR),3)VALOR_ALIMENTACAO,');
   Add('    ROUND(SUM(s.CUSTO_ALIMENTAR),3)VALOR_TOTAL_ALIMENTACAO,');
   Add('    ROUND(AVG(s.CUSTO_FIXO),3)CUSTO_FIXO,');
   Add('    ROUND(SUM(s.CUSTO_FIXO),3)CUSTO_FIXO_TOTAL,');
   Add('    ROUND(AVG(s.CUSTO_SANIDADE),3)CUSTO_SANIDADE,');
   Add('    ROUND(SUM(s.CUSTO_SANIDADE),3)CUSTO_TOTAL_SANIDADE,');
   Add('    ROUND(');
   Add('     (SUM(s.CUSTO_COMPRA)+');
   Add('     SUM(s.CUSTO_ALIMENTAR)+');
   Add('     SUM(s.CUSTO_FIXO)+');
   Add('     SUM(s.CUSTO_SANIDADE))/COUNT(*)');
   Add('     ,3)VALOR_TOTAL_ANIMAL,');
   Add('     ROUND(');
   Add('     (SUM(s.CUSTO_COMPRA)+');
   Add('     SUM(s.CUSTO_ALIMENTAR)+');
   Add('     SUM(s.CUSTO_FIXO)+');
   Add('     SUM(s.CUSTO_SANIDADE))');
   Add('     ,3)VALOR_TOTAL,');
   Add('     ROUND((SUM(s.CUSTO_ALIMENTAR)/COUNT(*))/AVG(s.DIAS_CONF),3)VALOR_ALI_CAB_DIA,');
   Add('     ROUND((SUM(s.CUSTO_FIXO)/COUNT(*))/AVG(s.DIAS_CONF),3)VALOR_FIXO_CAB_DIA,');
   Add('     ROUND((SUM(s.CUSTO_SANIDADE)/COUNT(*))/AVG(s.DIAS_CONF),3)VALOR_SANIDADE_CAB_DIA,');
   Add('     ROUND(');
   Add('       (SUM(s.CUSTO_SANIDADE)/COUNT(*)+');
   Add('       SUM(s.CUSTO_ALIMENTAR)/COUNT(*)+');
   Add('       SUM(s.CUSTO_FIXO)/COUNT(*))/AVG(s.DIAS_CONF)');
   Add('     ,3)CustoDiarioCabeca,');
   Add('     ROUND(');
   Add('       (SUM(s.CUSTO_SANIDADE)+');
   Add('       SUM(s.CUSTO_ALIMENTAR)+');
   Add('       SUM(s.CUSTO_FIXO))/AVG(s.DIAS_CONF)');
   Add('     ,3)CustoDiarioTotal');
   Add('   FROM ANIMAL_SAIDA s');
   Add('   LEFT JOIN ANIMAL a  ON a.ID=s.ID_ANIMAL');
   Add('   LEFT JOIN CURRAIS c ON c.ID=a.ID_LOCAL');
   Add('   LEFT JOIN AUX_REBANHO ar ON ar.ID=a.ID_REBANHO');
   Add('   LEFT JOIN PRODUTORES p ON p.ID=a.ID_PRODUTOR');
   Add('   LEFT JOIN PROPRIEDADES p2 ON p2.ID=a.ID_PROPRIEDADE');
   Add('   LEFT JOIN LOTE_SAIDA ls ON ls.ID=a.ID_LOTESAIDA');
   Add('   LEFT JOIN PRODUTORES p3 ON p3.ID = ls.ID_PRODUTOR_DESTINO');
   Add('   LEFT JOIN PROPRIEDADES p4 ON p4.ID=ls.ID_DESTINO');
   Add('   WHERE 1=1');
   Add(vFiltro);
   Add('   GROUP BY s.LOTE_SAIDA,ar.NOME,p3.NOME,p4.NOME,p.nome,p2.nome');
   Add('   )Y');
   Open;
   if not TRelSaidaSintetico.IsEmpty then
    ppRepRelSaida.Print;
 end
end;

procedure TSerRel.AbreRelSaidaSinteticoInd(vFiltro: string);
begin
 with TRelSaidaSintetico,TRelSaidaSintetico.sql do
 begin
   Clear;
   Add('SELECT');
   Add('     Y.*,');
   Add('     CASE');
   Add('      WHEN GTP_REAL_ARROBA>0  THEN');
   Add('          CONSUMO_MS_KG_CAB_TOTAL/GTP_REAL_ARROBA');
   Add('         ELSE');
   Add('         0');
   Add('      END EFICIENCIA_BIO,');
   Add('      CASE');
   Add('        WHEN (PESO_SAIDA>0 AND PESO_ENT_CONF>0) THEN');
   Add('          ((CONSUMO_MS_KG_CAB_DIA*100)/((PESO_SAIDA+PESO_ENT_CONF)/2))');
   Add('        ELSE');
   Add('         0');
   Add('      END CONSUMO_MS_PV,');
   Add('      CASE');
   Add('        WHEN (GMD_TOTAL>0) THEN');
   Add('         (CONSUMO_MS_KG_CAB_DIA/GMD_TOTAL)');
   Add('        ELSE');
   Add('         0');
   Add('      END CONVERSAO_ALIMENTAR,');
   Add('      CASE');
   Add('        WHEN (CONSUMO_MS_KG_CAB_DIA>0) THEN');
   Add('         (GMD_TOTAL/ CONSUMO_MS_KG_CAB_DIA)');
   Add('        ELSE');
   Add('         0');
   Add('      END EFICIENCIA_ALIMENTAR');
   Add('   FROM');
   Add('   (SELECT');
   Add('    s.LOTE_SAIDA,');
   Add('    MAX(s.DATA_SAIDA)DATA_SAIDA,');
   Add('    min(DATA_ENT_CONF) DATA_ENT_CONF,');
   Add('    ar.NOME Rebanho,');
   Add('    p3.NOME ProdutorDestino,');
   Add('    p4.NOME PropriedadeDestino,');
   Add('    p.NOME ProdutorOrigem,');
   Add('    p2.NOME PropriedadeOrigem,');
   Add('    COUNT(*) QTD_CAB,');
   Add('    AVG(s.DIAS_CONF)DIAS_CONF,');
   Add('    ROUND(AVG(s.PESO_ENT_CONF),3)PESO_ENT_CONF,');
   Add('    ROUND(AVG(s.PESO_ENT_CONF_ARROB),3)PESO_ENT_CONF_ARROBA,');
   Add('    ROUND(AVG(s.PESO_SAIDA),3)PESO_SAIDA,');
   Add('    ROUND(AVG(s.PESO_SAIDA_ARROB),3)PESO_SAIDA_ARROBA,');
   Add('    ROUND(AVG(s.PESO_PROJ),3)PESO_PROJ,');
   Add('    ROUND((AVG(s.PESO_PROJ)/30),3)PESO_PROJ_ARROBA,');
   Add('    ROUND((MIN(s.PESO_SAIDA)),3)PESO_MIN_SAIDA,');
   Add('    ROUND((MIN(s.PESO_SAIDA) * (AVG(s.RC)/100))/15,3)PESO_MIN_ARROBA,');
   Add('    ROUND((MAX(s.PESO_SAIDA)),3)PESO_MAX_SAIDA,');
   Add('    ROUND((MAX(s.PESO_SAIDA)*(AVG(s.RC)/100))/15,3)PESO_MAX_ARROBA,');
   Add('    ROUND(AVG(s.GMD_DIAS_CONF),3)GMD_TOTAL,');
   Add('    ROUND((AVG(s.PESO_CARCACA_REAL)-(AVG(s.PESO_ENT_CONF)/2))/AVG(s.DIAS_CONF),3) GMD_TOTAL_ARROBA,');
   Add('    ROUND(AVG(s.GTP_REAL),3)GTP_REAL,');
   Add('    ROUND(AVG(s.PESO_SAIDA_ARROB)-AVG(s.PESO_ENT_CONF_ARROB),3)GTP_REAL_ARROBA,');
   Add('    ROUND(SUM(s.GTP_REAL),3)GTP_TOTAL,');
   Add('    ROUND((AVG(s.PESO_SAIDA_ARROB)-AVG(s.PESO_ENT_CONF_ARROB))*COUNT(*),3) GTP_TOTAL_ARROBA,');
   Add('    ROUND(AVG(s.PESO_CARCACA_REAL),3)PESO_CARCACA,');
   Add('    ROUND(AVG(ls.PESO_CARCACA_TOTAL),3)TOTAL_PESO_CARCACA,');
   Add('    ROUND(SUM(s.PESO_SAIDA_ARROB),3) ARROBA_TOTAL,');
   Add('    ROUND(SUM(s.PESO_SAIDA),3) PESO_SAIDA_TOTAL,     ');
   Add('    ROUND(COALESCE(AVG(s.RC),50),3)RC,');
   Add('    ROUND(AVG(s.CONSUMO_MN_KG_CAB_DIA),3)CONSUMO_MN_KG_CAB_DIA,');
   Add('    ROUND(AVG(s.CONSUMO_MS_KG_CAB_DIA),3)CONSUMO_MS_KG_CAB_DIA,');
   Add('    ROUND(AVG(s.CONSUMO_MN_KG_CAB_TOTAL),3)CONSUMO_MN_KG_CAB_TOTAL,');
   Add('    ROUND(AVG(s.CONSUMO_MS_KG_CAB_TOTAL),3)CONSUMO_MS_KG_CAB_TOTAL,');
   Add('    ROUND(SUM(s.CONSUMO_MN_KG_CAB_TOTAL),3)CONSUMO_MN_TOTAL,');
   Add('    ROUND(SUM(s.CONSUMO_MS_KG_CAB_TOTAL),3)CONSUMO_MS_TOTAL,');
   Add('    CASE');
   Add('      WHEN SUM(s.GMD_DIAS_CONF)>0 then');
   Add('       ROUND(SUM(s.CONSUMO_MS_KG_CAB_TOTAL)/SUM(s.GMD_DIAS_CONF),3)');
   Add('      ELSE');
   Add('       0');
   Add('     END CONVERSAO,');
   Add('     CASE');
   Add('      WHEN SUM(s.GTP_REAL)>0 then');
   Add('       ROUND(SUM(s.CONSUMO_MS_KG_CAB_TOTAL)/SUM(s.GTP_REAL),3)');
   Add('      ELSE');
   Add('       0');
   Add('     END EFI_BIOLOGICA,');
   Add('    ROUND(AVG(s.CUSTO_COMPRA),3)VALOR_COMPRA,');
   Add('    ROUND(AVG(s.CUSTO_COMPRA)/AVG(s.PESO_ENT_CONF_ARROB),2)VALOR_COMPRA_ARR,');
   Add('    ROUND(SUM(s.CUSTO_COMPRA)/SUM(s.PESO_ENT_CONF_ARROB),2)VALOR_TOTAL_COMPRA_ARR,');
   Add('    ROUND(SUM(s.CUSTO_COMPRA),3)VALOR_TOTAL_COMPRA,');
   Add('    ROUND(AVG(s.CUSTO_ALIMENTAR),3)VALOR_ALIMENTACAO,');
   Add('    ROUND(SUM(s.CUSTO_ALIMENTAR),3)VALOR_TOTAL_ALIMENTACAO,');
   Add('    ROUND(AVG(s.CUSTO_FIXO),3)CUSTO_FIXO,');
   Add('    ROUND(SUM(s.CUSTO_FIXO),3)CUSTO_FIXO_TOTAL,');
   Add('    ROUND(AVG(s.CUSTO_SANIDADE),3)CUSTO_SANIDADE,');
   Add('    ROUND(SUM(s.CUSTO_SANIDADE),3)CUSTO_TOTAL_SANIDADE,');
   Add('    ROUND(');
   Add('     (SUM(s.CUSTO_COMPRA)+');
   Add('     SUM(s.CUSTO_ALIMENTAR)+');
   Add('     SUM(s.CUSTO_FIXO)+');
   Add('     SUM(s.CUSTO_SANIDADE))/COUNT(*)');
   Add('     ,3)VALOR_TOTAL_ANIMAL,');
   Add('     ROUND(');
   Add('     (SUM(s.CUSTO_COMPRA)+');
   Add('     SUM(s.CUSTO_ALIMENTAR)+');
   Add('     SUM(s.CUSTO_FIXO)+');
   Add('     SUM(s.CUSTO_SANIDADE))');
   Add('     ,3)VALOR_TOTAL,');
   Add('     ROUND((SUM(s.CUSTO_ALIMENTAR)/COUNT(*))/AVG(s.DIAS_CONF),3)VALOR_ALI_CAB_DIA,');
   Add('     ROUND((SUM(s.CUSTO_FIXO)/COUNT(*))/AVG(s.DIAS_CONF),3)VALOR_FIXO_CAB_DIA,');
   Add('     ROUND((SUM(s.CUSTO_SANIDADE)/COUNT(*))/AVG(s.DIAS_CONF),3)VALOR_SANIDADE_CAB_DIA,');
   Add('     ROUND(');
   Add('       (SUM(s.CUSTO_SANIDADE)/COUNT(*)+');
   Add('       SUM(s.CUSTO_ALIMENTAR)/COUNT(*)+');
   Add('       SUM(s.CUSTO_FIXO)/COUNT(*))/AVG(s.DIAS_CONF)');
   Add('     ,3)CustoDiarioCabeca,');
   Add('     ROUND(');
   Add('       (SUM(s.CUSTO_SANIDADE)+');
   Add('       SUM(s.CUSTO_ALIMENTAR)+');
   Add('       SUM(s.CUSTO_FIXO))/AVG(s.DIAS_CONF)');
   Add('     ,3)CustoDiarioTotal,');
   Add('   avg(s.GMD_DIAS_CONF)GMD_DIAS_CONF,');
   Add('   avg(s.GMD_DIAS_ALIMENTAR)GMD_DIAS_ALIMNTAR,');
   Add('   avg(s.GMD_DIAS_TOTAL)GMD_DIAS_TOTAL,');
   Add('   avg(s.GMD_RC)GMD_RC,');
   Add('   AVG(GTP_ARROB_P_CONF)GTP_ARROB_P_CONF,');
   Add('   AVG(GTP_ARROB_P_ENT)GTP_ARROB_P_ENT,');
   Add('   AVG(PESO_CARCACA_PROJ)PESO_CARCACA_PROJ ,');
   Add('   AVG(GMD_PROJ)GMD_PROJ,');
   Add('   AVG(GTP_PROJ)GTP_PROJ,');
   Add('   AVG(CUSTO_DIARIO_D_CONF)CUSTO_DIARIO_D_CONF,');
   Add('   AVG(CUSTO_DIARIO_D_ALIMENTAR)CUSTO_DIARIO_D_ALIMENTAR,');
   Add('   AVG(CUSTO_PRODUCAO)CUSTO_PRODUCAO,');
   Add('   AVG(CUSTO_ARROB_REAL)CUSTO_ARROB_REAL,');
   Add('   AVG(S.VALOR_VENDA)VALOR_VENDA,');
   Add('   AVG(S.VALOR_ARROB_VENDA)VALOR_ARROB_VENDA,');
   Add('   AVG(S.LUCRO_LIQUI)LUCRO_LIQUI,');
   Add('   SUM(CUSTO_DIARIO_D_TOTAL) CUSTO_DIARIO_D_TOTAL,');
   Add('   AVG(CUSTO_DIARIO_D_CONF) * avg(s.GMD_DIAS_CONF) CUSTO_DIARIO_D_CONF_TOTAL,');
   Add('   SUM(s.GMD_DIAS_ALIMENTAR) CUSTO_DIARIO_D_ALIMENTAR_TOTAL,');
   Add('   SUM(CUSTO_PRODUCAO)CUSTO_PRODUCAO_TOTAL,');
   Add('   SUM(CUSTO_ARROB_REAL)CUSTO_ARROB_REAL_TOTAL,');
   Add('   SUM(S.VALOR_VENDA) VALOR_VENDA_TOTAL,');
   Add('   SUM(S.VALOR_ARROB_VENDA) VALOR_ARROB_VENDA_TOTAL,');
   Add('   SUM(S.LUCRO_LIQUI)LUCRO_LIQUI_TOTAL,');
   Add('   SUM(s.DIAS_CONF)DIAS_CONF_TOTAL,');
   Add('   SUM(s.DIAS_ALIMENTAR) DIAS_ALIMENTAR_TOTAL');
   Add('   FROM ANIMAL_SAIDA s');
   Add('   LEFT JOIN ANIMAL a  ON a.ID=s.ID_ANIMAL');
   Add('   LEFT JOIN CURRAIS c ON c.ID=a.ID_LOCAL');
   Add('   LEFT JOIN AUX_REBANHO ar ON ar.ID=a.ID_REBANHO');
   Add('   LEFT JOIN PRODUTORES p ON p.ID=a.ID_PRODUTOR');
   Add('   LEFT JOIN PROPRIEDADES p2 ON p2.ID=a.ID_PROPRIEDADE');
   Add('   LEFT JOIN LOTE_SAIDA ls ON ls.ID=a.ID_LOTESAIDA');
   Add('   LEFT JOIN PRODUTORES p3 ON p3.ID = ls.ID_PRODUTOR_DESTINO');
   Add('   LEFT JOIN PROPRIEDADES p4 ON p4.ID=ls.ID_DESTINO');
   Add('   WHERE 1=1');
   Add(vFiltro);
   Add('   GROUP BY s.LOTE_SAIDA,ar.NOME,p3.NOME,p4.NOME,p.nome,p2.nome');
   Add('   )Y');
   Open;
   if not TRelSaidaSintetico.IsEmpty then
    ppRepRelSaidaInd.Print;
 end
end;

procedure TSerRel.AbrirHistMovRebanho(vFiltro: string);
begin
 with qryrelhistmovRebanho,qryrelhistmovRebanho.SQL do
 begin
   Clear;
   Add('SELECT');
   Add('hmr."DATA",');
   Add('a.IDENTIFICACAO_1,');
   Add('a.IDENTIFICACAO_2,');
   Add('ro.NOME RebanhoOrigem,');
   Add('rd.NOME RebanhoDestino');
   Add('FROM HIST_MOV_REBANHO hmr');
   Add('JOIN AUX_REBANHO ro ON ro.id=hmr.ID_REBANHO_ORIGEM');
   Add('JOIN AUX_REBANHO rd ON rd.id=hmr.ID_REBANHO_DESTINO');
   Add('JOIN ANIMAL a ON a.id=hmr.ID_ANIMAL ');
   Add('where A.status>-1');
   Add(vFiltro);
   Open;
 end;
end;

procedure TSerRel.ppDetailBand1BeforePrint(Sender: TObject);
begin
  ppShapeGreen.Visible  := false;
  ppShapeYwllow.Visible := false;
  ppShapeRed.Visible    := false;
  ppShapeGreen.Visible  :=(RelEstoquePrevALERTA.AsInteger>=10) and (RelEstoquePrevCONSUMOMEDIODIA.AsInteger>0);
  ppShapeYwllow.Visible :=(RelEstoquePrevALERTA.AsInteger<10)  and (RelEstoquePrevCONSUMOMEDIODIA.AsInteger>0);
  ppShapeRed.Visible    :=(RelEstoquePrevALERTA.AsInteger<=0)  and (RelEstoquePrevCONSUMOMEDIODIA.AsInteger>0);
end;

procedure TSerRel.ppDetailBand4AfterGenerateLastDetail(Sender: TObject);
begin
 if FileExists(frmPrincipal.PathLogoJPG)=true then
  ppImgLogoCli1.Picture.LoadFromFile(frmPrincipal.PathLogoJPG)
 else
  ppImgLogoCli1.Picture:=nil;
end;

procedure TSerRel.ppGroupHeaderBand12BeforePrint(Sender: TObject);
begin
  ppLblPropriedade.Text := serviceDB.vNomePropriedade;
end;

procedure TSerRel.ppHeaderBand12BeforeGenerate(Sender: TObject);
begin
  ppLblLS.Text := 'Lote de Saída: '+serviceDB.qryGridLoteSaidaID.AsString;
end;

procedure TSerRel.ppHeaderBand16BeforePrint(Sender: TObject);
begin
//  TThread.CreateAnonymousThread(
//   procedure
//   begin
//    TThread.Synchronize(TThread.CurrentThread,
//    procedure ()
//    begin
     if FileExists(frmPrincipal.PathLogoJPG)=true then
      ppImgLogoCliente.Picture.LoadFromFile(frmPrincipal.PathLogoJPG)
     else
      ppImgLogoCliente.Picture:=nil;
//    end);
//   end).Start;
end;

procedure TSerRel.ppHeaderBand19BeforePrint(Sender: TObject);
begin
 TThread.CreateAnonymousThread(
   procedure
   begin
    TThread.Synchronize(TThread.CurrentThread,
    procedure ()
    begin
     if FileExists(frmPrincipal.PathLogoJPG)=true then
      ppImgCliEstoqueAtual.Picture.LoadFromFile(frmPrincipal.PathLogoJPG)
     else
      ppImgCliEstoqueAtual.Picture:=nil;
    end);
   end).Start;
end;

procedure TSerRel.ppHeaderBand1BeforePrint(Sender: TObject);
begin
  TThread.CreateAnonymousThread(
   procedure
   begin
    TThread.Synchronize(TThread.CurrentThread,
    procedure ()
    begin
     if FileExists(frmPrincipal.PathLogoJPG)=true then
      ppImgLogoCli.Picture.LoadFromFile(frmPrincipal.PathLogoJPG)
     else
      ppImgLogoCli.Picture:=nil;
    end);
   end).Start;
end;

procedure TSerRel.ppHeaderBand20BeforePrint(Sender: TObject);
begin
  TThread.CreateAnonymousThread(
   procedure
   begin
    TThread.Synchronize(TThread.CurrentThread,
    procedure ()
    begin
     if FileExists(frmPrincipal.PathLogoJPG)=true then
      ppImgEstoqueExtrato.Picture.LoadFromFile(frmPrincipal.PathLogoJPG)
     else
      ppImgEstoqueExtrato.Picture:=nil;
    end);
   end).Start;
end;

procedure TSerRel.ppHeaderBand3BeforePrint(Sender: TObject);
begin
 TThread.CreateAnonymousThread(
   procedure
   begin
    TThread.Synchronize(TThread.CurrentThread,
    procedure ()
    begin
       if FileExists(frmPrincipal.PathLogoJPG)=true then
        ppImgLogoCli1.Picture.LoadFromFile(frmPrincipal.PathLogoJPG)
       else
        ppImgLogoCli1.Picture:=nil;
    end);
   end).Start;
end;

procedure TSerRel.ppHeaderBand4BeforePrint(Sender: TObject);
begin
  TThread.CreateAnonymousThread(
   procedure
   begin
    TThread.Synchronize(TThread.CurrentThread,
    procedure ()
    begin
      if FileExists(frmPrincipal.PathLogoJPG)=true then
      ppImgCli.Picture.LoadFromFile(frmPrincipal.PathLogoJPG)
     else
      ppImgCli.Picture:=nil;
    end);
   end).Start;
end;

procedure TSerRel.ppHeaderBand5BeforePrint(Sender: TObject);
begin
  TThread.CreateAnonymousThread(
   procedure
   begin
    TThread.Synchronize(TThread.CurrentThread,
    procedure ()
    begin
     if FileExists(frmPrincipal.PathLogoJPG)=true then
      ppImage6.Picture.LoadFromFile(frmPrincipal.PathLogoJPG)
     else
      ppImage6.Picture:=nil;
    end);
   end).Start;
end;

procedure TSerRel.ppRepRelAnimalVeiculoPreviewFormClose(Sender: TObject);
begin
  ShowMessage('Relrório gerado com sucesso!')
end;

procedure TSerRel.RelEstoquePrevisao;
begin
end;

procedure TSerRel.RelRelacaoEntradaAnimal(idFazenda, DataIni, DataFim,
  vFiltro: string);
begin
 with RelEntradasAnimal,RelEntradasAnimal.SQL do
 begin
   Clear;
   Add('SELECT Y.*,');
   Add('(Y.PESO_BALANCAO_ORIGEM-PESO_BALANCAO_DESTINO) QUEBRA_BALANCAO ');
   Add('FROM ');
   Add('(SELECT');
   Add('g.NUMERO||''-''||g.UF||''-''||g.UF GTA,');
   Add('pr.nome PropriedadeOrigem,');
   Add('p.nome ProdutorOrigem,');
   Add('CAST(AN.DATA_PROC AS DATE)DATA_PROCESSAMENTO ,');
   Add('COUNT(*) QTDE_ANIMAIS,');
   Add('COALESCE(AVG(G.PESO_B_ORIGEM),0)PESO_BALANCAO_ORIGEM,');
   Add('COALESCE(AVG(G.PESO_B_DESTINO),0)PESO_BALANCAO_DESTINO,');
   Add('COALESCE(AVG(AN.PESO_ENTRADA),0) MEDIA_IND_ENTRADA');
   Add('FROM animal an');
   Add('join produtores p on p.id=an.ID_PRODUTOR_ORIGEM');
   Add('JOIN PROPRIEDADES pr ON pr.ID=p.ID_PROPRIEDADE');
   Add('LEFT JOIN gta g ON g.ID=an.GTA_ID');
   Add('WHERE AN.STATUS=1 AND AN.ID_PROPRIEDADE=:idFazenda');
   Add('AND CAST(AN.DATA_PROC AS DATE) BETWEEN :DataIni AND :DataFim');
   if vFiltro.Length>0 then
    Add(vFiltro);
   Add('group by g.NUMERO||''-''||g.UF||''-''||g.UF,p.nome,pr.nome,AN.DATA_PROC)Y');
   ParamByName('idFazenda').AsString := idFazenda;
   ParamByName('DataIni').AsString   := DataIni;
   ParamByName('DataFim').AsString   := DataFim;
   Open;
   if IsEmpty then
    frmPrincipal.MyShowMessage('Não existe dados para esses filtros!',false)
   else
    ppReportEntradaAnimal.Print;
 end;
end;

end.
