CREATE OR ALTER PROCEDURE TOOLS_ATUALIZA_FORN
AS
DECLARE VARIABLE ID_FORN INTEGER;
BEGIN
  DELETE FROM ANIMAL_FORNECIMENTO_CONF;
  FOR SELECT ID FROM FORNECIMENTO_CONF
  WHERE STATUS=1 AND REALIZADO_MN_KG>0
  INTO:ID_FORN
  DO 
  BEGIN
	 INSERT INTO ANIMAL_FORNECIMENTO_CONF(
     ID_ANIMAL,
     ID_FORNECIMENTO,
      DATA_FORNECIMENTO,
      TRATO,
      ID_LOTE,
      ID_CURRAL,
      CONSUMO_MN,
      CONSUMO_MS,
      IMS_PV,
      CUSTO,
      PESO_MEDIO
     )
     SELECT
     B.ID,
     A.ID,
     A.DATA_FORN,
     A.TRATO,
     A.ID_LOTE,
     A.ID_LOCAL,
     CAST(A.REALIZADO_MN_KG AS DOUBLE PRECISION)/CAST(A.QTD_CAB AS DOUBLE PRECISION) ConsumoMn,
     CAST(A.REALIZADO_MN_KG AS DOUBLE PRECISION)/CAST(A.QTD_CAB AS DOUBLE PRECISION)*(CAST(MS_RACAO AS DOUBLE PRECISION)/100)ConsumoMs,
     (((CAST(A.REALIZADO_MN_KG AS DOUBLE PRECISION)/A.QTD_CAB)*(CAST(A.MS_RACAO AS DOUBLE PRECISION)/100)*100)/
     CAST(MEDIA_PESO AS DOUBLE PRECISION))IMS_PV,
     A.CUSTO_TOTAL_TRATO/A.QTD_CAB,
     A.MEDIA_PESO
     FROM FORNECIMENTO_CONF A
     JOIN ANIMAL B ON A.ID_LOCAL=B.ID_LOCAL
     WHERE A.ID=:ID_FORN;
  END
END
